import type { Ability, AdventureNode, EnemyTemplate, GearItem, GearSetBonusDefinition, Talent } from "./types";
import { createStatusEffect } from "./statusEffects";

export const ABILITIES: Record<string, Ability> = {
  strike: {
    id: "strike", name: "Strike", description: "A reliable weapon attack.", energyCost: 0,
    cooldownTurns: 1, target: "enemy", damageType: "physical", power: 5, scalingStat: "strength", icon: "⚔", branch: "core",
  },
  guard: {
    id: "guard", name: "Guard", description: "Gain 6 Guard until the next turn.", energyCost: 2,
    target: "self", icon: "◆", branch: "core", effect: "guard", vfx: "guard",
  },
  quickSlash: {
    id: "quickSlash", name: "Quick Slash", description: "Deal Physical Damage equal to 50% of your Physical Power.", energyCost: 1,
    target: "enemy", damageType: "physical", powerScaling: 0.5, icon: "◢", branch: "shadow",
  },
  TwinStrike: {
    id: "TwinStrike", name: "Twin Strike", description: "Strike twice. Each hit deals Physical Damage equal to 50% of your Physical Power and triggers on-hit effects separately.", energyCost: 2,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.5, hits: 2, icon: "⫸", branch: "shadow",
  },
  PoisonStab: {
    id: "PoisonStab", name: "Poison Stab", description: "Deal Physical Damage equal to 50% of your Physical Power and apply 1 Poison.", energyCost: 3,
    target: "enemy", damageType: "physical", powerScaling: 0.5, icon: "†", branch: "shadow", effect: "poison",
  },
  PoisonCloud: {
    id: "PoisonCloud", name: "Poison Cloud", description: "Apply 2 Poison to all enemies without dealing direct damage.", energyCost: 3,
    cooldownTurns: 2, target: "all_enemies", dealsDamage: false, icon: "☁", branch: "shadow", effect: "poison", statusStacks: 2, vfx: "poison_cloud",
  },
  Contagion: {
    id: "Contagion", name: "Contagion", description: "Copy all Poison stacks from the selected enemy to another random living enemy.", energyCost: 2,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", spreadTargetStatus: "poison", icon: "☣", branch: "shadow",
  },
  Stealth: {
    id: "Stealth", name: "Stealth", description: "Enemies cannot target you until the end of your next turn.", energyCost: 2,
    cooldownTurns: 3, target: "self", icon: "◌", branch: "shadow", effect: "stealth", statusDuration: 2, statusExpiresAtTurnStart: false,
  },
  Evasion: {
    id: "Evasion", name: "Evasion", description: "Gain 60% Dodge Chance until your next turn. Dodge Chance cannot exceed 50%.", energyCost: 2,
    cooldownTurns: 3, target: "self", icon: "↝", branch: "shadow", effect: "evasion", statusDuration: 1, statusExpiresAtTurnStart: true, vfx: "evasion",
  },
  Neurotoxin: {
    id: "Neurotoxin", name: "Neurotoxin", description: "Consume all Poison on an enemy to Stun it.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", consumeTargetStatus: "poison", icon: "⌁", branch: "shadow", effect: "stun", vfx: "neurotoxin",
  },
  VenomousStrike: {
    id: "VenomousStrike", name: "Venomous Strike", description: "Deal Physical Damage equal to 100% of your Physical Power and apply 2 Poison. Deals double damage if the target is already Poisoned.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 1, icon: "†", branch: "shadow", effect: "poison", statusStacks: 2,
    damageModifiers: [{ id: "venomous-strike-poisoned", name: "Venomous Strike", description: "Deals double damage to Poisoned targets.", multiplier: 2, targetHasAnyStatus: ["poison"] }], vfx: "venomous_strike",
  },
  Flurry: {
    id: "Flurry", name: "Flurry", description: "Attack five times, dealing Physical Damage equal to 40% of your Physical Power per hit. Each hit chooses a random enemy and can trigger on-hit effects.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.4, hits: 5, randomTargetPerHit: true, attackSequenceDurationMultiplier: 1.4, icon: "≋", branch: "shadow", vfx: "flurry",
  },
  Ambush: {
    id: "Ambush", name: "Ambush", description: "Can only be used while Stealthed. Deal Physical Damage equal to 150% of your Physical Power with +50% Critical Strike Chance.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 1.5, requiredSelfStatus: "stealth", critChanceBonusWithStatus: { status: "stealth", bonus: 0.5 }, icon: "◈", branch: "shadow", vfx: "ambush",
  },
  ToxicExplosion: {
    id: "ToxicExplosion", name: "Toxic Explosion", description: "Detonate all Poison on the target, dealing its remaining duration damage immediately and removing Poison.", energyCost: 5,
    cooldownTurns: 2, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", detonateStatus: "poison", icon: "☣", branch: "shadow", vfx: "toxic_explosion",
  },
  Venomborn: {
    id: "Venomborn", name: "Venomborn", description: "Consume all Poison on the target to heal for the damage it would deal over its full duration.", energyCost: 2,
    cooldownTurns: 6, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", consumeStatusForHealing: "poison", icon: "♨", branch: "shadow", vfx: "venomborn",
  },
  LightningStrike: {
    id: "LightningStrike", name: "Lightning Strike", description: "Deal 50% Physical Power as Physical Damage and 50% Magical Power as Lightning Damage, then apply Electrified for 3 turns.", energyCost: 4,
    cooldownTurns: 4, target: "enemy", damageComponents: [{ damageType: "physical", powerScaling: 0.5 }, { damageType: "lightning", powerScaling: 0.5 }], effect: "electrified", statusDuration: 3, icon: "ϟ", branch: "shadow", vfx: "lightning_strike",
  },
  Focus: {
    id: "Focus", name: "Focus", description: "Reset all your other ability cooldowns.", energyCost: 1,
    cooldownTurns: 6, target: "self", effect: "reset_cooldowns", icon: "◎", branch: "shadow", vfx: "focus",
  },
  Recouperate: {
    id: "Recouperate", name: "Recuperate", description: "Restore 50% of your maximum Energy.", energyCost: 1,
    cooldownTurns: 4, target: "self", energyRestorePercentOfMax: 0.5, icon: "◉", branch: "shadow", vfx: "recuperate",
  },
  SharpenedBlade: {
    id: "SharpenedBlade", name: "Sharpened Blade", description: "Deal 100% Physical Power as damage. This attack ignores Guard and Barrier.", energyCost: 2,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 1, ignoresAbsorption: true, icon: "†", branch: "shadow", vfx: "sharpened_blade",
  },
  SlowingVenom: {
    id: "SlowingVenom", name: "Slowing Venom", description: "Consume 50% of the target's Poison, apply Slowed, and deal 75% Physical Power as damage.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 0.75, requiredTargetStatus: "poison", consumeTargetStatus: "poison", consumeTargetStatusRatio: 0.5,
    statusApplications: [{ status: "slowed" }], icon: "⌁", branch: "shadow", vfx: "slowing_venom",
  },
  WeakeningVenom: {
    id: "WeakeningVenom", name: "Weakening Venom", description: "Consume 50% of the target's Poison, apply Vulnerable and Weaken, and deal 60% Physical Power as damage.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 0.6, requiredTargetStatus: "poison", consumeTargetStatus: "poison", consumeTargetStatusRatio: 0.5,
    statusApplications: [{ status: "vulnerable" }, { status: "weaken" }], icon: "⌁", branch: "shadow", vfx: "weakening_venom",
  },
  RabidVenom: {
    id: "RabidVenom", name: "Rabid Venom", description: "Consume 50% of the target's Poison, apply Reckless, and deal 75% Physical Power as damage.", energyCost: 3,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.75, requiredTargetStatus: "poison", consumeTargetStatus: "poison", consumeTargetStatusRatio: 0.5,
    statusApplications: [{ status: "reckless" }], icon: "⌁", branch: "shadow", vfx: "rabid_venom",
  },
  PinpointSlice: {
    id: "PinpointSlice", name: "Pinpoint Slice", description: "Deal 75% Physical Power as damage. Your next damaging ability is guaranteed to critically strike.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.75, grantsNextCritical: true, icon: "⊙", branch: "shadow", vfx: "pinpoint_slice",
  },
  TraumaticPuncture: {
    id: "TraumaticPuncture", name: "Traumatic Puncture", description: "Deal 75% Physical Power as damage. A critical strike also applies Weaken and 2 Bleed.", energyCost: 3,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.75,
    statusApplications: [{ status: "weaken", onlyOnCritical: true }, { status: "bleed", stacks: 2, onlyOnCritical: true }], icon: "‡", branch: "shadow",
  },
  SliceAndDice: {
    id: "SliceAndDice", name: "Slice and Dice", description: "Attack six times for 15% Physical Power per hit. Critical hits apply Exhausted. Each hit triggers on-hit effects.", energyCost: 5,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.15, hits: 6, attackSequenceDurationMultiplier: 1.4,
    statusApplications: [{ status: "exhausted", onlyOnCritical: true }], icon: "≋", branch: "shadow", vfx: "slice_and_dice",
  },
  CheapShot: {
    id: "CheapShot", name: "Cheap Shot", description: "Stun the target and apply 5 Bleed. Can only be used while Stealthed.", energyCost: 4,
    cooldownTurns: 1, target: "enemy", dealsDamage: false, requiredSelfStatus: "stealth", effect: "stun",
    statusApplications: [{ status: "bleed", stacks: 5 }], icon: "‡", branch: "shadow",
  },
  Pandemic: {
    id: "Pandemic", name: "Pandemic", description: "Copy every debuff on the target to all other living enemies.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, spreadAllTargetDebuffs: true, icon: "☣", branch: "shadow", vfx: "pandemic",
  },
  LightSpeed: {
    id: "LightSpeed", name: "Light Speed", description: "Deal 50% Physical Power as Physical Damage and 100% Magical Power as Lightning Damage, apply Electrified, then immediately begin a new turn.", energyCost: 6,
    cooldownTurns: 5,
    target: "enemy", damageComponents: [{ damageType: "physical", powerScaling: 0.5 }, { damageType: "lightning", powerScaling: 1 }],
    statusApplications: [{ status: "electrified" }], grantsImmediateTurn: true, icon: "ϟ", branch: "shadow", vfx: "light_speed", immediateTurnVfx: "light_speed_turn",
  },
  ChainAssassination: {
    id: "ChainAssassination", name: "Chain Assassination", description: "Deal 125% Physical Power as damage. While Stealthed, gain +25% Critical Strike Chance. A kill refunds the Energy spent and resets the cooldown.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 1.25,
    critChanceBonusWithStatus: { status: "stealth", bonus: 0.25 }, refundEnergyOnKill: true, resetCooldownOnKill: true, killVfx: "chain_assassination", icon: "◈", branch: "shadow",
  },
  CullTheWeak: {
    id: "CullTheWeak", name: "Cull the Weak", description: "Deal 25% Physical Power as Physical Damage and 25% Magical Power as Arcane Damage. Both gain 20% damage per unique debuff on the target.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageComponents: [{ damageType: "physical", powerScaling: 0.25 }, { damageType: "arcane", powerScaling: 0.25 }],
    damagePerTargetDebuff: 0.2, icon: "◎", branch: "shadow", vfx: "cull_the_weak",
  },
  Epidemic: {
    id: "Epidemic", name: "Epidemic", description: "Apply 10 Poison to all enemies and gain Stealth until the end of your next turn.", energyCost: 3,
    cooldownTurns: 10, target: "all_enemies", dealsDamage: false, effect: "poison", statusStacks: 10,
    selfStatusApplications: [{ status: "stealth", duration: 2, expiresAtTurnStart: false }], icon: "☣", branch: "shadow", vfx: "epidemic",
  },
  VoltageStab: {
    id: "VoltageStab", name: "Voltage Stab", description: "Deal Lightning Damage equal to 35% of your Magical Power. If the target is Electrified, restore 2% of your maximum Health and gain +2 Energy regeneration next turn.", energyCost: 0,
    cooldownTurns: 2, target: "enemy", damageType: "lightning", powerScaling: 0.35,
    conditionalSelfEffects: [{ targetHasStatus: "electrified", healPercentMaxHp: 0.02, nextTurnEnergyRegen: 2, vfx: "voltage_siphon" }], icon: "ϟ", branch: "shadow",
  },
  crushingBlow: {
    id: "crushingBlow", name: "Crushing Blow", description: "A heavy strike that leaves the enemy vulnerable.", energyCost: 4,
    target: "enemy", damageType: "physical", power: 12, scalingStat: "strength", icon: "✦", branch: "brute", effect: "vulnerable",
  },
  groundSlam: {
    id: "groundSlam", name: "Ground Slam", description: "Damage all enemies with a chance to stun.", energyCost: 6,
    target: "all_enemies", damageType: "physical", power: 7, scalingStat: "strength", icon: "✹", branch: "brute", effect: "stun",
  },
  sever: {
    id: "sever", name: "Sever", description: "A swift cut that applies Bleed for 3 turns.", energyCost: 3,
    target: "enemy", damageType: "shadow", power: 7, scalingStat: "agility", icon: "◢", branch: "shadow", effect: "bleed",
  },
  venom: {
    id: "venom", name: "Venom Edge", description: "Poison an enemy and deal light damage.", energyCost: 4,
    target: "enemy", damageType: "shadow", power: 5, scalingStat: "agility", icon: "⌁", branch: "shadow", effect: "poison",
  },
  arcaneBolt: {
    id: "arcaneBolt", name: "Arcane Bolt", description: "Deal Arcane Damage equal to 75% of your Magical Power.", energyCost: 1,
    cooldownTurns: 1, target: "enemy", damageType: "arcane", powerScaling: 0.75, icon: "✧", branch: "arcanist", vfx: "arcane_bolt",
  },
  Frostbolt: {
    id: "Frostbolt", name: "Frostbolt", description: "Deal Frost Damage equal to 50% of your Magical Power and have a 50% chance to apply Slowed.", energyCost: 3,
    cooldownTurns: 1, target: "enemy", damageType: "frost", powerScaling: 0.5, statusApplications: [{ status: "slowed", chance: 0.5 }], icon: "❄", branch: "arcanist", vfx: "frostbolt",
  },
  ArcaneBlast: {
    id: "ArcaneBlast", name: "Arcane Blast", description: "Deal Arcane Damage equal to 20% of your Magical Power and apply 1 Arcane Wound. Each Arcane Wound increases Arcane Blast damage by 10%.", energyCost: 1,
    target: "enemy", damageType: "arcane", powerScaling: 0.2, statusApplications: [{ status: "arcaneWound" }], damagePerTargetStatusStack: { status: "arcaneWound", multiplier: 0.1 }, freeAgainstTargetStatus: "arcaneCharge", icon: "✦", branch: "arcanist", vfx: "arcane_blast",
  },
  Fireball: {
    id: "Fireball", name: "Fireball", description: "Deal Fire Damage equal to 100% of your Magical Power and apply 2 Burn.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "fire", powerScaling: 1, statusApplications: [{ status: "burn", stacks: 2 }], icon: "●", branch: "arcanist", vfx: "fireball",
  },
  LightningBeam: {
    id: "LightningBeam", name: "Lightning Beam", description: "Strike random enemies four times for 20% Magical Power as Lightning Damage per hit. Each hit has a 20% chance to apply Electrified.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", damageType: "lightning", powerScaling: 0.2, hits: 4, randomTargetPerHit: true, statusApplications: [{ status: "electrified", chance: 0.2 }], icon: "ϟ", branch: "arcanist", vfx: "lightning_beam",
  },
  Thunderstorm: {
    id: "Thunderstorm", name: "Thunderstorm", description: "Strike random enemies six times for 30% Magical Power as Lightning Damage per hit. Hits against Electrified enemies deal 50% more damage.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageType: "lightning", powerScaling: 0.3, hits: 6, randomTargetPerHit: true,
    damageModifiers: [{ id: "thunderstorm-electrified", name: "Conductive Storm", description: "Thunderstorm deals 50% more damage to Electrified enemies.", targetHasAnyStatus: ["electrified"], multiplier: 1.5 }], icon: "ϟ", branch: "arcanist", vfx: "thunderstorm",
  },
  DeepFreeze: {
    id: "DeepFreeze", name: "Deep Freeze", description: "Deal 75% Magical Power as Frost Damage and apply Slowed. If the target is already Slowed, apply Stunned instead.", energyCost: 4,
    cooldownTurns: 4, target: "enemy", damageType: "frost", powerScaling: 0.75, statusApplications: [{ status: "slowed" }],
    conditionalStatusReplacement: { status: "slowed", whenTargetHas: "slowed", replacement: "stunned" }, icon: "❄", branch: "arcanist", vfx: "deep_freeze",
  },
  ArcaneOverload: {
    id: "ArcaneOverload", name: "Arcane Overload", description: "Deal 50% Magical Power as Arcane Damage, apply 3 Arcane Wounds, and mark the target with Arcane Charge. Your next Arcane Blast against that target costs 0 Energy.", energyCost: 3,
    cooldownTurns: 3, target: "enemy", damageType: "arcane", powerScaling: 0.5,
    statusApplications: [{ status: "arcaneWound", stacks: 3 }, { status: "arcaneCharge" }], icon: "✹", branch: "arcanist", vfx: "arcane_overload",
  },
  Combustion: {
    id: "Combustion", name: "Combustion", description: "Consume all Burn on the target and deal its remaining damage immediately. If this kills the target, spread half its Burn stacks to all other enemies.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, requiredTargetStatus: "burn", detonateStatus: "burn",
    spreadDetonatedStatusOnKillRatio: 0.5, spreadOnKillVfx: "combustion_spread", icon: "🔥", branch: "arcanist", vfx: "combustion",
  },
  ArcaneCombustion: {
    id: "ArcaneCombustion", name: "Arcane Combustion", description: "Consume all Arcane Wounds on the target. Deal 50% Magical Power as Fire Damage per stack consumed and apply an equal number of Burn stacks.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", requiredTargetStatus: "arcaneWound", consumeTargetStatus: "arcaneWound",
    consumeTargetStatusForDamage: { status: "arcaneWound", damageType: "fire", powerScalingPerStack: 0.5, applyStatus: "burn", appliedStacksPerConsumedStack: 1 }, icon: "✹", branch: "arcanist", vfx: "arcane_combustion",
  },
  Thundersnow: {
    id: "Thundersnow", name: "Thundersnow", description: "Hit all enemies for a combined 60% Magical Power as Frost and Lightning Damage. Apply Slowed to every target and Electrified to one random target.", energyCost: 5,
    cooldownTurns: 3, target: "all_enemies", damageComponents: [{ damageType: "frost", powerScaling: 0.3 }, { damageType: "lightning", powerScaling: 0.3 }],
    statusApplications: [{ status: "slowed" }], randomSingleStatusApplication: { status: "electrified" }, icon: "❄", branch: "arcanist", vfx: "thundersnow",
  },
  SelfImmolation: {
    id: "SelfImmolation", name: "Self Immolation", description: "Apply 5 Burn to yourself and the selected enemy.", energyCost: 1,
    cooldownTurns: 5, target: "enemy", dealsDamage: false, effect: "burn", statusStacks: 5,
    selfStatusApplications: [{ status: "burn", stacks: 5 }], selfStatusVfx: "self_immolation", icon: "🔥", branch: "arcanist", vfx: "self_immolation",
  },
  ArcaneBarrier: {
    id: "ArcaneBarrier", name: "Arcane Barrier", description: "Gain Barrier equal to 50% of your Magical Power for 3 turns.", energyCost: 1,
    cooldownTurns: 5, target: "self", dealsDamage: false, effect: "barrier", statusDuration: 3,
    statusStackPowerScaling: { power: "magical", scaling: 0.5 }, icon: "◇", branch: "arcanist", vfx: "arcane_barrier",
  },
  FrozenPath: {
    id: "FrozenPath", name: "Frozen Path", description: "Gain 30% Dodge Chance for 3 turns. Dodge Chance cannot exceed 50%.", energyCost: 1,
    cooldownTurns: 5, target: "self", dealsDamage: false, effect: "frozenPath", statusDuration: 3, statusMagnitude: 0.3,
    icon: "❄", branch: "arcanist", vfx: "frozen_path",
  },
  Conductor: {
    id: "Conductor", name: "Conductor", description: "Stun all enemies and yourself for 1 turn.", energyCost: 1,
    cooldownTurns: 5, target: "all_enemies", dealsDamage: false, effect: "stunned", statusDuration: 1,
    selfStatusApplications: [{ status: "stunned", duration: 1 }], selfStatusVfx: "conductor", icon: "ϟ", branch: "arcanist", vfx: "conductor",
  },
  Firestorm: {
    id: "Firestorm", name: "Firestorm", description: "Deal Fire Damage equal to 25% of your Magical Power to all enemies, then apply 2 Burn to all enemies and yourself.", energyCost: 5,
    cooldownTurns: 3, target: "all_enemies", damageType: "fire", powerScaling: 0.25, effect: "burn", statusStacks: 2,
    selfStatusApplications: [{ status: "burn", stacks: 2 }], selfStatusVfx: "firestorm", icon: "🔥", branch: "arcanist", vfx: "firestorm",
  },
  siphon: {
    id: "siphon", name: "Essence Siphon", description: "Deal damage and recover 2 Energy.", energyCost: 4,
    target: "enemy", damageType: "arcane", power: 7, scalingStat: "intelligence", icon: "◎", branch: "arcanist", effect: "energy",
  },
};

export const TALENT_TREE_CANVAS = { width: 4015, height: 2850 } as const;

const TALENT_NODES: Talent[] = [
  { id: "origin", name: "Wayfarer's Spark", description: "Your first step. Unlocks Strike and Guard.", branch: "core", kind: "class", tier: 0, cost: 0, requires: [], position: { x: 32.258, y: 50 }, icon: "✦", shape: "square" },
  { id: "brute_1", name: "Brute", description: "+2 Strength.", branch: "brute", kind: "class", tier: 1, cost: 1, requires: ["origin"], position: { x: 27.419, y: 50 }, icon: "◆", shape: "square", combat: { passive: { stats: { strength: 2 } } } },
  { id: "shadow_1", name: "Shadow", description: "+2 Agility. Unlocks Quick Slash.", branch: "shadow", kind: "class", tier: 1, cost: 1, requires: ["origin"], position: { x: 37.097, y: 50 }, icon: "◈", shape: "square", abilityId: "quickSlash", combat: { passive: { stats: { agility: 2 } } } },
  { id: "arcanist_1", name: "Arcanist", description: "+2 Intelligence. Unlocks Arcane Bolt.", branch: "arcanist", kind: "class", tier: 1, cost: 1, requires: ["origin"], position: { x: 32.258, y: 43.75 }, icon: "✧", shape: "square", abilityId: "arcaneBolt", effectNotes: "Passive Bonus: +2 Intelligence.\nAbility: Arcane Bolt\nCost: 1 Energy\nCooldown: 1 turn\nDeal 75% Magical Power as Arcane Damage.", combat: { passive: { stats: { intelligence: 2 } } } },
  { id: "cultist_1", name: "Cultist", description: "Unlocks the Cultist path.", branch: "cultist", kind: "class", tier: 1, cost: 1, requires: ["origin"], position: { x: 27.397, y: 56.25 }, icon: "☾", shape: "square" },
  { id: "talent_1", name: "Immaculate Timing", description: "+2 Agility. +5 Initiative.", branch: "shadow", kind: "passive", tier: 2, cost: 1, requires: ["shadow_1"], position: { x: 41.935, y: 50 }, icon: "✦", shape: "circle", combat: { passive: { stats: { agility: 2 }, initiative: 5 } } },
  { id: "talent_2", name: "Twin Strike", description: "Strike twice for 50% Physical Power per hit. Each hit triggers on-hit effects.", branch: "shadow", kind: "ability", tier: 3, cost: 1, requires: ["talent_1"], position: { x: 45.967, y: 45.312 }, icon: "✦", shape: "square", abilityId: "TwinStrike" },
  { id: "talent_3", name: "Poison Stab", description: "Deal 50% Physical Power as damage and apply 1 Poison.", branch: "shadow", kind: "ability", tier: 3, cost: 1, requires: ["talent_1"], position: { x: 45.967, y: 54.688 }, icon: "✦", shape: "square", abilityId: "PoisonStab" },
  { id: "talent_4", name: "Honed Skills", description: "+3% Critical Strike Chance.", branch: "shadow", kind: "passive", tier: 4, cost: 1, requires: ["talent_2"], position: { x: 50, y: 45.312 }, icon: "✦", shape: "circle", combat: { passive: { critChance: 0.03 } } },
  { id: "talent_5", name: "Precision", description: "+3% Hit Chance.", branch: "shadow", kind: "passive", tier: 4, cost: 1, requires: ["talent_3"], position: { x: 50, y: 54.688 }, icon: "✦", shape: "circle", combat: { passive: { hitChance: 0.03 } } },
  { id: "talent_6", name: "Elusiveness", description: "+3% Dodge Chance.", branch: "shadow", kind: "passive", tier: 5, cost: 1, requires: ["talent_4"], position: { x: 50, y: 39.844 }, icon: "✦", shape: "circle", combat: { passive: { dodgeChance: 0.03 } } },
  { id: "talent_7", name: "Stamina", description: "+1 Max Energy.", branch: "shadow", kind: "passive", tier: 5, cost: 1, requires: ["talent_4"], position: { x: 54.032, y: 45.312 }, icon: "✦", shape: "circle", combat: { passive: { maxEnergy: 1 } } },
  { id: "talent_8", name: "Setup", description: "+4 Initiative.", branch: "shadow", kind: "passive", tier: 5, cost: 1, requires: ["talent_5"], position: { x: 50, y: 60.157 }, icon: "✦", shape: "circle", combat: { passive: { initiative: 4 } } },
  { id: "talent_9", name: "Spell Dodger", description: "+2 Magic Resistance.", branch: "shadow", kind: "passive", tier: 5, cost: 1, requires: ["talent_5"], position: { x: 54.032, y: 54.688 }, icon: "✦", shape: "circle", combat: { passive: { magicResistance: 2 } } },
  { id: "talent_10", name: "Poison Cloud", description: "Apply 2 Poison to all enemies without dealing direct damage.", branch: "shadow", kind: "ability", tier: 6, cost: 1, requires: ["talent_9", "talent_34"], position: { x: 58.06451612903226, y: 56.25 }, icon: "✦", shape: "square", abilityId: "PoisonCloud" },
  { id: "talent_11", name: "Stealth", description: "Enemies cannot target you until the end of your next turn.", branch: "shadow", kind: "ability", tier: 6, cost: 1, requires: ["talent_7", "talent_34"], position: { x: 58.06451612903226, y: 43.75 }, icon: "✦", shape: "square", abilityId: "Stealth" },
  { id: "talent_12", name: "Poison Coating", description: "Each hit has a 50% chance to apply 1 Poison.", branch: "shadow", kind: "passive", tier: 6, cost: 1, requires: ["talent_8"], position: { x: 54.032, y: 64.844 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "poison-coating", name: "Poison Coating", description: "Each hit has a 50% chance to apply 1 Poison.", event: "on_hit", chance: 0.5, effects: [{ type: "apply_status", status: createStatusEffect("poison"), target: "target" }] }] } },
  { id: "talent_13", name: "Adrenaline", description: "Each hit has a 10% chance to restore 1 Energy.", branch: "shadow", kind: "passive", tier: 6, cost: 1, requires: ["talent_6"], position: { x: 54.032, y: 35.156 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "adrenaline", name: "Adrenaline", description: "Each hit has a 10% chance to restore 1 Energy.", event: "on_hit", chance: 0.1, effects: [{ type: "gain_energy", amount: 1, target: "self" }] }] } },
  { id: "talent_14", name: "Evasion", description: "Increase your Dodge Chance by 60% until your next turn. Dodge Chance cannot exceed 50%.", branch: "shadow", kind: "ability", tier: 7, cost: 1, requires: ["talent_13"], position: { x: 58.064, y: 35.156 }, icon: "✦", shape: "square", abilityId: "Evasion" },
  { id: "talent_15", name: "Neurotoxin", description: "Consume all Poison on an enemy to Stun it.", branch: "shadow", kind: "ability", tier: 7, cost: 1, requires: ["talent_12"], position: { x: 58.065, y: 64.844 }, icon: "✦", shape: "square", abilityId: "Neurotoxin", effectNotes: "Consume all Poison on an enemy to Stun it." },
  { id: "talent_16", name: "Opportunist", description: "Deal 50% more damage while attacking from Stealth.", branch: "shadow", kind: "passive", tier: 7, cost: 1, requires: ["talent_11"], position: { x: 62.097, y: 45.312 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "opportunist", name: "Opportunist", description: "Deal 50% more damage while attacking from Stealth.", multiplier: 1.5, attackerHasAnyStatus: ["stealth"] }] } },
  { id: "talent_17", name: "Blisters", description: "Deal 20% more Physical Damage to Poisoned enemies.", branch: "shadow", kind: "passive", tier: 7, cost: 1, requires: ["talent_10"], position: { x: 62.097, y: 54.688 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "blisters", name: "Blisters", description: "Deal 20% more Physical Damage to Poisoned enemies.", multiplier: 1.2, damageTypes: ["physical"], targetHasAnyStatus: ["poison"] }] } },
  { id: "talent_18", name: "Agile", description: "+2 Agility.", branch: "shadow", kind: "passive", tier: 8, cost: 1, requires: ["talent_14"], position: { x: 62.097, y: 35.156 }, icon: "✦", shape: "circle", combat: { passive: { stats: { agility: 2 } } } },
  { id: "talent_19", name: "Smarts", description: "+2 Intelligence.", branch: "shadow", kind: "passive", tier: 8, cost: 1, requires: ["talent_15"], position: { x: 62.097, y: 64.844 }, icon: "✦", shape: "circle", combat: { passive: { stats: { intelligence: 2 } } } },
  { id: "talent_20", name: "Venomous Strike", description: "Deal 100% Physical Power as damage and apply 2 Poison. Deals double damage if the target is already Poisoned.", branch: "shadow", kind: "ability", tier: 9, cost: 1, requires: ["talent_19"], position: { x: 66.129, y: 69.531 }, icon: "✦", shape: "square", abilityId: "VenomousStrike" },
  { id: "talent_21", name: "Toxicology", description: "Your Poison deals 10% more damage.", branch: "shadow", kind: "passive", tier: 9, cost: 1, requires: ["talent_19"], position: { x: 66.129, y: 60.157 }, icon: "✦", shape: "circle", effectNotes: "Your Poison deals 10% more damage.", combat: { passive: { statusDamage: { poison: 0.1 } } } },
  { id: "talent_22", name: "Virulence", description: "Your Poison deals 10% more damage.", branch: "shadow", kind: "passive", tier: 8, cost: 1, requires: ["talent_17"], position: { x: 66.129, y: 54.688 }, icon: "✦", shape: "circle", effectNotes: "Your Poison deals 10% more damage.", combat: { passive: { statusDamage: { poison: 0.1 } } } },
  { id: "talent_23", name: "Electrified", description: "Your attacks have a 20% chance to apply Electrified.", branch: "shadow", kind: "passive", tier: 9, cost: 1, requires: ["talent_18"], position: { x: 66.129, y: 39.844 }, icon: "✦", shape: "circle", effectNotes: "Your attacks have a 20% chance to apply Electrified.", combat: { triggers: [{ id: "electrified-strikes", name: "Electrified", description: "Each hit has a 20% chance to apply Electrified.", event: "on_hit", chance: 0.2, effects: [{ type: "apply_status", status: createStatusEffect("electrified"), target: "target" }] }] } },
  { id: "talent_24", name: "Flurry", description: "Attack five times for 40% Physical Power per hit. Each hit chooses a random enemy and can trigger on-hit effects.", branch: "shadow", kind: "ability", tier: 9, cost: 1, requires: ["talent_18"], position: { x: 66.129, y: 30.469 }, icon: "✦", shape: "square", abilityId: "Flurry", effectNotes: "Cooldown: 2 turns\nCost: 4 Energy\nAttack five times for 40% Physical Power per hit. Each hit chooses a random enemy and can trigger on-hit effects." },
  { id: "talent_25", name: "Energized", description: "+1 Energy gained at the start of your turn.", branch: "shadow", kind: "passive", tier: 8, cost: 1, requires: ["talent_16"], position: { x: 66.129, y: 45.312 }, icon: "✦", shape: "circle", effectNotes: "+1 Energy gained at the start of your turn.", combat: { passive: { energyRegen: 1 } } },
  { id: "talent_26", name: "Ambush", description: "Can only be used while Stealthed. Deal 150% Physical Power as damage with +50% Critical Strike Chance.", branch: "shadow", kind: "ability", tier: 9, cost: 1, requires: ["talent_25"], position: { x: 70.161, y: 45.312 }, icon: "✦", shape: "square", abilityId: "Ambush", effectNotes: "Cost: 2 Energy\nCan only be used while Stealthed. Deal 150% Physical Power as damage with +50% Critical Strike Chance." },
  { id: "talent_27", name: "Toxic Explosion", description: "Detonate all Poison on the target, dealing its remaining duration damage immediately and removing Poison.", branch: "shadow", kind: "ability", tier: 9, cost: 1, requires: ["talent_22"], position: { x: 70.16129032258065, y: 54.6875 }, icon: "✦", shape: "square", abilityId: "ToxicExplosion", effectNotes: "Cost: 5 Energy\nCooldown: 2 turns\nDetonate all Poison on the target, dealing its remaining duration damage immediately and removing Poison." },
  { id: "talent_28", name: "Longevity", description: "Toxic Explosion now only removes half of the Poison stacks from the target.", branch: "shadow", kind: "passive", tier: 10, cost: 1, requires: ["talent_27"], position: { x: 70.161, y: 60.156 }, icon: "✦", shape: "circle", effectNotes: "Toxic Explosion now only removes half of the Poison stacks from the target.", combat: { abilityModifiers: [{ id: "longevity", name: "Longevity", description: "Toxic Explosion only removes half of the Poison stacks.", abilityIds: ["ToxicExplosion"], descriptionOverride: "Detonate all Poison on the target, dealing its remaining duration damage immediately and removing only half of its Poison stacks.", detonationRetainedStackRatio: 0.5 }] } },
  { id: "talent_29", name: "Maneuvers", description: "Ambush can be used outside Stealth, but deals 100% Physical Power and gains no bonus Critical Strike Chance when used that way.", branch: "shadow", kind: "passive", tier: 10, cost: 1, requires: ["talent_26"], position: { x: 70.161, y: 39.844 }, icon: "✦", shape: "circle", effectNotes: "Ambush can be used outside Stealth, but deals 100% Physical Power and gains no bonus Critical Strike Chance when used that way.", combat: { abilityModifiers: [{ id: "maneuvers", name: "Maneuvers", description: "Ambush can be used outside Stealth at 100% Physical Power without its bonus Critical Strike Chance.", abilityIds: ["Ambush"], descriptionOverride: "While Stealthed, deal 150% Physical Power as damage with +50% Critical Strike Chance. Outside Stealth, deal 100% Physical Power without bonus Critical Strike Chance.", allowWithoutRequiredSelfStatus: true, powerScalingWhenRequirementMissing: 1 }] } },
  { id: "talent_30", name: "Reapply", description: "After Neurotoxin consumes Poison, it applies 2 Poison.", branch: "shadow", kind: "passive", tier: 8, cost: 1, requires: ["talent_15"], position: { x: 58.065, y: 70.313 }, icon: "✦", shape: "circle", effectNotes: "After Neurotoxin consumes Poison, it applies 2 Poison.", combat: { abilityModifiers: [{ id: "reapply", name: "Reapply", description: "Neurotoxin applies 2 Poison after consuming the previous Poison.", abilityIds: ["Neurotoxin"], descriptionOverride: "Consume all Poison on an enemy to Stun it, then apply 2 Poison.", applyStatusAfterConsume: { status: "poison", stacks: 2 } }] } },
  { id: "talent_31", name: "Enduring Evasion", description: "Evasion grants 40% Dodge Chance but lasts for an additional turn.", branch: "shadow", kind: "passive", tier: 8, cost: 1, requires: ["talent_14"], position: { x: 58.06451612903226, y: 29.6875 }, icon: "✦", shape: "circle", effectNotes: "Evasion grants 40% Dodge Chance but lasts for an additional turn.", combat: { abilityModifiers: [{ id: "enduring-evasion", name: "Enduring Evasion", description: "Evasion grants 40% Dodge Chance for an additional turn.", abilityIds: ["Evasion"], descriptionOverride: "Increase your Dodge Chance by 40% until the end of your next turn. Dodge Chance cannot exceed 50%.", statusDuration: 2, statusMagnitude: 0.4, statusExpiresAtTurnStart: false }] } },
  { id: "talent_32", name: "Self Medicate", description: "Enemies that deal direct damage to you gain 1 Poison. You start each combat with 2 Poison.", branch: "shadow", kind: "passive", tier: 10, cost: 1, requires: ["talent_20"], position: { x: 70.16129032258065, y: 69.53125 }, icon: "✦", shape: "circle", effectNotes: "Enemies that deal direct damage to you gain 1 Poison. You start each combat with 2 Poison.", combat: { passive: { startingStatuses: [createStatusEffect("poison", { stacks: 2, sourcePower: 0, sourceId: "self-medicate" })] }, triggers: [{ id: "self-medicate-retaliation", name: "Self Medicate", description: "Enemies that deal direct damage to you gain 1 Poison.", event: "damage_taken", effects: [{ type: "apply_status", status: createStatusEffect("poison"), target: "target" }] }] } },
  { id: "talent_33", name: "Shock Stabs", description: "Your hits against Electrified targets have a 5% chance to Stun them.", branch: "shadow", kind: "passive", tier: 10, cost: 1, requires: ["talent_24"], position: { x: 70.16129032258065, y: 30.46875 }, icon: "✦", shape: "circle", effectNotes: "Your hits against Electrified targets have a 5% chance to Stun them.", combat: { triggers: [{ id: "shock-stabs", name: "Shock Stabs", description: "Hits against Electrified targets have a 5% chance to Stun.", event: "on_hit", chance: 0.05, conditions: { targetHasAnyStatus: ["electrified"] }, effects: [{ type: "apply_status", status: createStatusEffect("stunned"), target: "target" }] }] } },
  { id: "talent_34", name: "Recuperate", description: "Restore 50% of your maximum Energy.", branch: "shadow", kind: "ability", tier: 7, cost: 1, requires: [], position: { x: 58.06451612903226, y: 50 }, icon: "✦", shape: "square", abilityId: "Recouperate" },
  { id: "talent_35", name: "Venomborn", description: "Consume all Poison on the target to heal for the damage it would deal over its full duration.", branch: "shadow", kind: "ability", tier: 11, cost: 1, requires: ["talent_32"], position: { x: 74.19354838709677, y: 69.53125 }, icon: "✦", shape: "square", abilityId: "Venomborn", effectNotes: "Cost: 2 Energy\nCooldown: 6 turns\nConsume all Poison on the target to heal for its full-duration damage." },
  { id: "talent_36", name: "Lightning Strike", description: "Deal 50% Physical Power as Physical Damage and 50% Magical Power as Lightning Damage, then apply Electrified for 3 turns.", branch: "shadow", kind: "ability", tier: 11, cost: 1, requires: ["talent_33"], position: { x: 74.19354838709677, y: 30.46875 }, icon: "✦", shape: "square", abilityId: "LightningStrike", effectNotes: "Cost: 4 Energy\nCooldown: 4 turns\nDeal 50% Physical Power as Physical Damage and 50% Magical Power as Lightning Damage, then apply Electrified for 3 turns." },
  { id: "talent_37", name: "Focus", description: "Reset all your other ability cooldowns.", branch: "shadow", kind: "ability", tier: 10, cost: 1, requires: ["talent_27", "talent_26"], position: { x: 74.19354838709677, y: 50 }, icon: "✦", shape: "square", abilityId: "Focus", effectNotes: "Cost: 1 Energy\nCooldown: 6 turns\nReset all your other ability cooldowns." },
  { id: "talent_38", name: "Contagion", description: "Spread your Poison from one enemy to another random enemy.", branch: "shadow", kind: "ability", tier: 4, cost: 1, requires: ["talent_3"], position: { x: 45.96774193548387, y: 60.15625 }, icon: "✦", shape: "square", abilityId: "Contagion" },
  { id: "talent_39", name: "Sharpened Blade", description: "Deal 100% Physical Power as damage. This attack ignores Guard and Barrier.", branch: "shadow", kind: "ability", tier: 4, cost: 1, requires: ["talent_2"], position: { x: 45.96774193548387, y: 39.84375 }, icon: "✦", shape: "square", abilityId: "SharpenedBlade" },
  { id: "talent_40", name: "Resistance", description: "You are immune to Poison.", branch: "shadow", kind: "passive", tier: 12, cost: 1, requires: ["talent_35"], position: { x: 78.2258064516129, y: 64.84375 }, icon: "✦", shape: "circle", combat: { passive: { statusImmunities: ["poison"] } } },
  { id: "talent_41", name: "Thunderstruck", description: "You are immune to Electrified.", branch: "shadow", kind: "passive", tier: 12, cost: 1, requires: ["talent_36"], position: { x: 78.2258064516129, y: 35.15625 }, icon: "✦", shape: "circle", combat: { passive: { statusImmunities: ["electrified"] } } },
  { id: "talent_42", name: "Perfected Formula", description: "Whenever you apply Poison, apply 1 additional stack.", branch: "shadow", kind: "passive", tier: 11, cost: 1, requires: ["talent_37"], position: { x: 78.2258064516129, y: 54.6875 }, icon: "✦", shape: "circle", combat: { passive: { statusApplicationStacks: { poison: 1 } } } },
  { id: "talent_43", name: "Distraction", description: "Killing an enemy grants Stealth until the end of your next turn and makes your next ability cost 0 Energy.", branch: "shadow", kind: "passive", tier: 11, cost: 1, requires: ["talent_37"], position: { x: 78.2258064516129, y: 45.3125 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "distraction", name: "Distraction", description: "Killing an enemy grants Stealth until the end of your next turn and makes your next ability free.", event: "on_kill", effects: [{ type: "apply_status", status: createStatusEffect("stealth", { duration: 2, expiresAtTurnStart: false }), target: "self" }, { type: "apply_status", status: createStatusEffect("distraction", { duration: 1 }), target: "self" }] }] } },
  { id: "talent_44", name: "Extra Dose", description: "Your critical strikes always apply 2 Poison.", branch: "shadow", kind: "passive", tier: 7, cost: 1, requires: ["talent_12"], position: { x: 54.03225806451613, y: 70.3125 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "extra-dose", name: "Extra Dose", description: "Critical strikes apply 2 Poison.", event: "on_crit", effects: [{ type: "apply_status", status: createStatusEffect("poison", { stacks: 2 }), target: "target" }] }] } },
  { id: "talent_45", name: "Flow", description: "Your critical strikes restore 1 Energy.", branch: "shadow", kind: "passive", tier: 7, cost: 1, requires: ["talent_13"], position: { x: 54.03225806451613, y: 29.6875 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "flow", name: "Flow", description: "Critical strikes restore 1 Energy.", event: "on_crit", effects: [{ type: "gain_energy", amount: 1, target: "self" }] }] } },
  { id: "talent_46", name: "Slowing Venom", description: "Consume 50% of the target's Poison, apply Slowed, and deal 75% Physical Power as damage.", branch: "shadow", kind: "ability", tier: 8, cost: 1, requires: ["talent_44"], position: { x: 54.03225806451613, y: 75.78125 }, icon: "✦", shape: "square", abilityId: "SlowingVenom" },
  { id: "talent_47", name: "Weakening Venom", description: "Consume 50% of the target's Poison, apply Vulnerable and Weaken, and deal 60% Physical Power as damage.", branch: "shadow", kind: "ability", tier: 8, cost: 1, requires: ["talent_44"], position: { x: 58.06451612903226, y: 75.78125 }, icon: "✦", shape: "square", abilityId: "WeakeningVenom" },
  { id: "talent_48", name: "Rabid Venom", description: "Consume 50% of the target's Poison, apply Reckless, and deal 75% Physical Power as damage.", branch: "shadow", kind: "ability", tier: 8, cost: 1, requires: ["talent_44"], position: { x: 50, y: 75.78125 }, icon: "✦", shape: "square", abilityId: "RabidVenom" },
  { id: "talent_49", name: "Precise Incisions", description: "Rabid Venom, Slowing Venom, and Weakening Venom consume only 25% of the target's Poison.", branch: "shadow", kind: "passive", tier: 9, cost: 1, requires: ["talent_46", "talent_47", "talent_48"], position: { x: 54.03225806451613, y: 81.25 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [
    { id: "precise-incisions-slowing", name: "Precise Incisions", description: "Slowing Venom consumes only 25% of the target's Poison.", abilityIds: ["SlowingVenom"], descriptionOverride: "Consume 25% of the target's Poison, apply Slowed, and deal 75% Physical Power as damage.", statusConsumptionRatio: 0.25 },
    { id: "precise-incisions-weakening", name: "Precise Incisions", description: "Weakening Venom consumes only 25% of the target's Poison.", abilityIds: ["WeakeningVenom"], descriptionOverride: "Consume 25% of the target's Poison, apply Vulnerable and Weaken, and deal 60% Physical Power as damage.", statusConsumptionRatio: 0.25 },
    { id: "precise-incisions-rabid", name: "Precise Incisions", description: "Rabid Venom consumes only 25% of the target's Poison.", abilityIds: ["RabidVenom"], descriptionOverride: "Consume 25% of the target's Poison, apply Reckless, and deal 75% Physical Power as damage.", statusConsumptionRatio: 0.25 },
  ] } },
  { id: "talent_50", name: "Pinpoint Slice", description: "Deal 75% Physical Power as damage. Your next damaging ability is guaranteed to critically strike.", branch: "shadow", kind: "ability", tier: 8, cost: 1, requires: ["talent_45"], position: { x: 54.03225806451613, y: 24.21875 }, icon: "✦", shape: "square", abilityId: "PinpointSlice" },
  { id: "talent_51", name: "Traumatic Puncture", description: "Deal 75% Physical Power as damage. A critical strike also applies Weaken and 2 Bleed.", branch: "shadow", kind: "ability", tier: 8, cost: 1, requires: ["talent_45"], position: { x: 50, y: 24.21875 }, icon: "✦", shape: "square", abilityId: "TraumaticPuncture" },
  { id: "talent_52", name: "Slice and Dice", description: "Attack six times for 15% Physical Power per hit. Critical hits apply Exhausted. Each hit triggers on-hit effects.", branch: "shadow", kind: "ability", tier: 8, cost: 1, requires: ["talent_45"], position: { x: 58.06451612903226, y: 24.21875 }, icon: "✦", shape: "square", abilityId: "SliceAndDice" },
  { id: "talent_53", name: "Taste for Blood", description: "Whenever you critically strike, restore 1% of your maximum Health.", branch: "shadow", kind: "passive", tier: 9, cost: 1, requires: ["talent_51", "talent_52", "talent_50"], position: { x: 54.03225806451613, y: 18.75 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "taste-for-blood", name: "Taste for Blood", description: "Critical strikes restore 1% of your maximum Health.", event: "on_crit", effects: [{ type: "heal_percent_max_hp", ratio: 0.01, target: "self" }] }] } },
  { id: "talent_54", name: "Leech", description: "Restore Health equal to 5% of your Poison damage, rounded up.", branch: "shadow", kind: "passive", tier: 12, cost: 1, requires: ["talent_35"], position: { x: 78.2258064516129, y: 74.21875 }, icon: "✦", shape: "circle", combat: { passive: { statusDamageLeech: { poison: 0.05 } } } },
  { id: "talent_55", name: "Sweaty Aftermath", description: "Whenever you apply Electrified, also apply Wet.", branch: "shadow", kind: "passive", tier: 12, cost: 1, requires: ["talent_36"], position: { x: 78.2258064516129, y: 25.78125 }, icon: "✦", shape: "circle", combat: { passive: { statusApplicationCompanions: { electrified: ["wet"] } } } },
  { id: "talent_56", name: "Cheap Shot", description: "Stun the target and apply 5 Bleed. Can only be used while Stealthed.", branch: "shadow", kind: "ability", tier: 12, cost: 1, requires: ["talent_43", "talent_42"], position: { x: 82.25806451612904, y: 50 }, icon: "✦", shape: "square", abilityId: "CheapShot" },
  { id: "talent_57", name: "Pandemic", description: "Copy every debuff on the target to all other living enemies.", branch: "shadow", kind: "ability", tier: 13, cost: 1, requires: ["talent_40", "talent_42"], position: { x: 82.25806451612904, y: 60.15625 }, icon: "✦", shape: "square", abilityId: "Pandemic" },
  { id: "talent_58", name: "Light Speed", description: "Deal 50% Physical and 100% Magical damage, apply Electrified, and immediately begin a new turn.", branch: "shadow", kind: "ability", tier: 12, cost: 1, requires: ["talent_43", "talent_41"], position: { x: 82.25806451612904, y: 39.84375 }, icon: "✦", shape: "square", abilityId: "LightSpeed" },
  { id: "talent_59", name: "Chain Assassination", description: "Deal 125% Physical Power as damage. While Stealthed, gain +25% Critical Strike Chance. A kill refunds the Energy spent and resets the cooldown.", branch: "shadow", kind: "ability", tier: 12, cost: 1, requires: ["talent_43"], position: { x: 74.19354838709677, y: 39.84375 }, icon: "✦", shape: "square", abilityId: "ChainAssassination" },
  { id: "talent_60", name: "Cull the Weak", description: "Deal 25% Physical and 25% Magical damage. Both gain 20% damage per unique debuff on the target.", branch: "shadow", kind: "ability", tier: 12, cost: 1, requires: ["talent_42"], position: { x: 74.19354838709677, y: 60.15625 }, icon: "✦", shape: "square", abilityId: "CullTheWeak" },
  { id: "talent_61", name: "Hit and Run", description: "Whenever you deal damage, you have a 2% chance to gain Stealth until the end of your next turn.", branch: "shadow", kind: "passive", tier: 13, cost: 1, requires: ["talent_56"], position: { x: 86.29032258064517, y: 50 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "hit-and-run", name: "Hit and Run", description: "Damage dealt has a 2% chance to grant Stealth until the end of your next turn.", event: "on_hit", chance: 0.02, conditions: { minimumDamage: 1 }, effects: [{ type: "apply_status", status: createStatusEffect("stealth", { duration: 2, expiresAtTurnStart: false }), target: "self" }] }] } },
  { id: "talent_62", name: "Spot Weakness", description: "Deal 5% more damage per unique debuff on the target.", branch: "shadow", kind: "passive", tier: 14, cost: 1, requires: ["talent_57"], position: { x: 86.29032258064517, y: 60.15625 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "spot-weakness", name: "Spot Weakness", description: "Deal 5% more damage per unique target debuff.", multiplier: 1, multiplierPerTargetDebuff: 0.05 }] } },
  { id: "talent_63", name: "Avoidance", description: "+1 Max Energy. Take 3% less damage per unspent Energy.", branch: "shadow", kind: "passive", tier: 13, cost: 1, requires: ["talent_58"], position: { x: 86.29032258064517, y: 39.84375 }, icon: "✦", shape: "circle", combat: { passive: { maxEnergy: 1, incomingDamageReductionPerEnergy: 0.03 } } },
  { id: "talent_64", name: "Epidemic", description: "Apply 10 Poison to all enemies and gain Stealth until the end of your next turn.", branch: "shadow", kind: "ability", tier: 15, cost: 1, requires: ["talent_62"], position: { x: 90.32258064516128, y: 60.15625 }, icon: "✦", shape: "square", abilityId: "Epidemic" },
  { id: "talent_65", name: "Panic", description: "The first time you would die each combat, restore 20% of your maximum Health and gain Stealth for 2 turns.", branch: "shadow", kind: "passive", tier: 14, cost: 1, requires: ["talent_61"], position: { x: 90.32258064516128, y: 50 }, icon: "✦", shape: "circle", combat: { passive: { deathPreventionHealRatio: 0.2, deathPreventionStealthDuration: 2 } } },
  { id: "talent_66", name: "Voltage Stab", description: "Deal 35% Magical Power as Lightning Damage. Against an Electrified target, restore 2% of maximum Health and gain +2 Energy regeneration next turn.", branch: "shadow", kind: "ability", tier: 14, cost: 1, requires: ["talent_63"], position: { x: 90.32258064516128, y: 39.84375 }, icon: "✦", shape: "square", abilityId: "VoltageStab" },
  { id: "talent_67", name: "Recovery", description: "Whenever an enemy misses you, you have a 50% chance to restore 1 Energy.", branch: "shadow", kind: "passive", tier: 9, cost: 1, requires: ["talent_31"], position: { x: 62.096774193548384, y: 29.6875 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "recovery", name: "Recovery", description: "Enemy misses have a 50% chance to restore 1 Energy.", event: "enemy_missed", chance: 0.5, effects: [{ type: "gain_energy", amount: 1, target: "self" }] }] } },
  { id: "talent_68", name: "Fleetfooted", description: "+2% Dodge Chance.", branch: "shadow", kind: "passive", tier: 10, cost: 1, requires: ["talent_67"], position: { x: 62.096774193548384, y: 24.21875 }, icon: "✦", shape: "circle", combat: { passive: { dodgeChance: 0.02 } } },
  { id: "talent_69", name: "Spotting Opportunity", description: "Whenever an enemy misses you, apply Vulnerable to it.", branch: "shadow", kind: "passive", tier: 11, cost: 1, requires: ["talent_68"], position: { x: 66.12903225806451, y: 24.21875 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "spotting-opportunity", name: "Spotting Opportunity", description: "An enemy that misses you becomes Vulnerable.", event: "enemy_missed", effects: [{ type: "apply_status", status: createStatusEffect("vulnerable"), target: "target" }] }] } },
  { id: "talent_70", name: "Untouchable", description: "+2% Dodge Chance.", branch: "shadow", kind: "passive", tier: 12, cost: 1, requires: ["talent_69"], position: { x: 70.16129032258065, y: 24.21875 }, icon: "✦", shape: "circle", combat: { passive: { dodgeChance: 0.02 } } },
  { id: "talent_71", name: "Biding Time", description: "Whenever an enemy misses you, gain Fierce for 1 turn.", branch: "shadow", kind: "passive", tier: 13, cost: 1, requires: ["talent_70"], position: { x: 74.19354838709677, y: 24.21875 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "biding-time", name: "Biding Time", description: "Enemy misses grant Fierce for 1 turn.", event: "enemy_missed", effects: [{ type: "apply_status", status: createStatusEffect("fierce", { duration: 1 }), target: "self" }] }] } },
  { id: "talent_72", name: "Precise Strikes", description: "+2% Hit Chance.", branch: "shadow", kind: "passive", tier: 9, cost: 1, requires: ["talent_30"], position: { x: 62.096774193548384, y: 70.3125 }, icon: "✦", shape: "circle", combat: { passive: { hitChance: 0.02 } } },
  { id: "talent_73", name: "Break", description: "Whenever you Stun an enemy, restore 2% of your maximum Health.", branch: "shadow", kind: "passive", tier: 10, cost: 1, requires: ["talent_72"], position: { x: 62.096774193548384, y: 75.78125 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "break", name: "Break", description: "Stunning an enemy restores 2% of your maximum Health.", event: "enemy_stunned", effects: [{ type: "heal_percent_max_hp", ratio: 0.02, target: "self" }] }] } },
  { id: "talent_74", name: "Calculated Strikes", description: "+2% Hit Chance.", branch: "shadow", kind: "passive", tier: 11, cost: 1, requires: ["talent_73"], position: { x: 66.12903225806451, y: 75.78125 }, icon: "✦", shape: "circle", combat: { passive: { hitChance: 0.02 } } },
  { id: "talent_75", name: "Mischief", description: "Whenever you Stun an enemy, deal damage equal to 10% of its current Health.", branch: "shadow", kind: "passive", tier: 12, cost: 1, requires: ["talent_74"], position: { x: 70.16129032258065, y: 75.78125 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "mischief", name: "Mischief", description: "Stunning an enemy deals damage equal to 10% of its current Health.", event: "enemy_stunned", effects: [{ type: "damage_percent_current_hp", ratio: 0.1, target: "target" }] }] } },
  { id: "talent_76", name: "Regenerating Toxin", description: "Neurotoxin consumes only 50% of the target's Poison.", branch: "shadow", kind: "passive", tier: 13, cost: 1, requires: ["talent_75"], position: { x: 74.19354838709677, y: 75.78125 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "regenerating-toxin", name: "Regenerating Toxin", description: "Neurotoxin consumes only 50% of the target's Poison.", abilityIds: ["Neurotoxin"], descriptionOverride: "Consume 50% of the target's Poison to Stun it.", statusConsumptionRatio: 0.5 }] } },
  { id: "talent_77", name: "New Current", description: "Reduces the cooldown of Voltage Stab by 1 turn.", branch: "shadow", kind: "passive", tier: 15, cost: 1, requires: ["talent_66"], position: { x: 76.71232876712328, y: 34.375 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "new-current", name: "New Current", description: "Reduces the cooldown of Voltage Stab by 1 turn.", abilityIds: ["VoltageStab"], cooldownTurnsDelta: -1 }] } },
  { id: "talent_78", name: "Efficient Spread", description: "Reduces the energy cost of Epidemic by 1.", branch: "shadow", kind: "passive", tier: 16, cost: 1, requires: ["talent_64"], position: { x: 76.71232876712328, y: 65.625 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "efficient-spread", name: "Efficient Spread", description: "Reduces the energy cost of Epidemic by 1.", abilityIds: ["Epidemic"], energyCostDelta: -1 }] } },
  { id: "talent_79", name: "Arcane Mind", description: "+2 Intelligence. +3 Magic Resistance.", branch: "arcanist", kind: "passive", tier: 2, cost: 1, requires: ["arcanist_1"], position: { x: 27.397260273972602, y: 36.71875 }, icon: "✦", shape: "circle", combat: { passive: { stats: { intelligence: 2 }, magicResistance: 3 } } },
  { id: "talent_80", name: "Frostbolt", description: "Deal 50% Magical Power as Frost Damage and have a 50% chance to apply Slowed.", branch: "arcanist", kind: "ability", tier: 3, cost: 1, requires: ["talent_79"], position: { x: 29.45205479452055, y: 31.25 }, icon: "✦", shape: "square", abilityId: "Frostbolt" },
  { id: "talent_81", name: "Arcane Blast", description: "Deal 20% Magical Power as Arcane Damage and apply 1 Arcane Wound. Each stack increases Arcane Blast damage by 10%.", branch: "arcanist", kind: "ability", tier: 3, cost: 1, requires: ["talent_79"], position: { x: 25.34246575342466, y: 31.25 }, icon: "✦", shape: "square", abilityId: "ArcaneBlast", effectNotes: "Arcane Wound lasts 3 turns. Each stack increases Arcane Blast damage against the target by 10%." },
  { id: "talent_82", name: "Fireball", description: "Deal 100% Magical Power as Fire Damage and apply 2 Burn.", branch: "arcanist", kind: "ability", tier: 3, cost: 1, requires: ["talent_79"], position: { x: 21.232876712328768, y: 32.03125 }, icon: "✦", shape: "square", abilityId: "Fireball" },
  { id: "talent_83", name: "Lightning Beam", description: "Hit random enemies four times for 20% Magical Power as Lightning Damage per hit. Each hit has a 20% chance to apply Electrified.", branch: "arcanist", kind: "ability", tier: 3, cost: 1, requires: ["talent_79"], position: { x: 33.56164383561644, y: 32.03125 }, icon: "✦", shape: "square", abilityId: "LightningBeam" },
  { id: "talent_84", name: "Critical Burn", description: "+2% Critical Strike Chance.", branch: "arcanist", kind: "passive", tier: 4, cost: 1, requires: ["talent_82"], position: { x: 18.493150684931507, y: 27.34375 }, icon: "✦", shape: "circle", combat: { passive: { critChance: 0.02 } } },
  { id: "talent_85", name: "Aimed Spells", description: "+2% Hit Chance.", branch: "arcanist", kind: "passive", tier: 4, cost: 1, requires: ["talent_81"], position: { x: 25.34246575342466, y: 25.78125 }, icon: "✦", shape: "circle", combat: { passive: { hitChance: 0.02 } } },
  { id: "talent_86", name: "Frozen Armor", description: "+2 Armor.", branch: "arcanist", kind: "passive", tier: 4, cost: 1, requires: ["talent_80"], position: { x: 29.45205479452055, y: 25.78125 }, icon: "✦", shape: "circle", combat: { passive: { armor: 2 } } },
  { id: "talent_87", name: "Lightning Fast", description: "+2 Initiative.", branch: "arcanist", kind: "passive", tier: 4, cost: 1, requires: ["talent_83"], position: { x: 36.3013698630137, y: 27.34375 }, icon: "✦", shape: "circle", combat: { passive: { initiative: 2 } } },
  { id: "talent_88", name: "Kindled Precision", description: "+2% Critical Strike Chance.", branch: "arcanist", kind: "passive", tier: 5, cost: 1, requires: ["talent_84"], position: { x: 15.753424657534246, y: 27.34375 }, icon: "✦", shape: "circle", combat: { passive: { critChance: 0.02 } } },
  { id: "talent_89", name: "Fire Within", description: "+1 Max Energy.", branch: "arcanist", kind: "passive", tier: 5, cost: 1, requires: ["talent_84"], position: { x: 18.493150684931507, y: 22.65625 }, icon: "✦", shape: "circle", combat: { passive: { maxEnergy: 1 } } },
  { id: "talent_90", name: "Charged Reflexes", description: "+2 Initiative.", branch: "arcanist", kind: "passive", tier: 5, cost: 1, requires: ["talent_87"], position: { x: 39.04109589041096, y: 27.34375 }, icon: "✦", shape: "circle", combat: { passive: { initiative: 2 } } },
  { id: "talent_91", name: "Increased Voltage", description: "+1 Max Energy.", branch: "arcanist", kind: "passive", tier: 5, cost: 1, requires: ["talent_87"], position: { x: 36.3013698630137, y: 22.65625 }, icon: "✦", shape: "circle", combat: { passive: { maxEnergy: 1 } } },
  { id: "talent_92", name: "Arcane Accuracy", description: "+2% Hit Chance.", branch: "arcanist", kind: "passive", tier: 5, cost: 1, requires: ["talent_85"], position: { x: 22.602739726027394, y: 25.78125 }, icon: "✦", shape: "circle", combat: { passive: { hitChance: 0.02 } } },
  { id: "talent_93", name: "Glacial Plating", description: "+2 Armor.", branch: "arcanist", kind: "passive", tier: 5, cost: 1, requires: ["talent_86"], position: { x: 32.19178082191781, y: 25.78125 }, icon: "✦", shape: "circle", combat: { passive: { armor: 2 } } },
  { id: "talent_94", name: "Engulf", description: "Critical strikes with your spells apply 1 Burn.", branch: "arcanist", kind: "passive", tier: 6, cost: 1, requires: ["talent_88"], position: { x: 15.753424657534246, y: 22.65625 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "engulf", name: "Engulf", description: "Critical strikes with your spells apply 1 Burn.", event: "on_crit", conditions: { abilityBranches: ["arcanist"] }, effects: [{ type: "apply_status", status: createStatusEffect("burn"), target: "target" }] }] } },
  { id: "talent_95", name: "Elemental Surprise", description: "Deal 20% more damage until you take damage for the first time each combat.", branch: "arcanist", kind: "passive", tier: 6, cost: 1, requires: ["talent_90"], position: { x: 39.04109589041096, y: 22.65625 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "elemental-surprise", name: "Elemental Surprise", description: "Deal 20% more damage until you take damage for the first time each combat.", multiplier: 1.2, requiresPlayerUndamaged: true }] } },
  { id: "talent_96", name: "Invigorate", description: "Hitting an enemy with Arcane Wound has a 20% chance to restore 2 Energy.", branch: "arcanist", kind: "passive", tier: 6, cost: 1, requires: ["talent_85"], position: { x: 25.34246575342466, y: 21.09375 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "invigorate", name: "Invigorate", description: "Hitting an enemy with Arcane Wound has a 20% chance to restore 2 Energy.", event: "on_hit", chance: 0.2, conditions: { targetHasAnyStatus: ["arcaneWound"] }, effects: [{ type: "gain_energy", amount: 2, target: "self" }] }] } },
  { id: "talent_97", name: "Comparative Momentum", description: "Applying Slowed to an enemy has a 30% chance to restore 1 Energy.", branch: "arcanist", kind: "passive", tier: 6, cost: 1, requires: ["talent_86"], position: { x: 29.45205479452055, y: 21.09375 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "comparative-momentum", name: "Comparative Momentum", description: "Applying Slowed to an enemy has a 30% chance to restore 1 Energy.", event: "status_applied", chance: 0.3, conditions: { appliedAnyStatus: ["slowed"] }, effects: [{ type: "gain_energy", amount: 1, target: "self" }] }] } },
  { id: "talent_98", name: "Confidence", description: "Deal 20% more damage until your first miss each combat.", branch: "arcanist", kind: "passive", tier: 6, cost: 1, requires: ["talent_92"], position: { x: 22.602739726027394, y: 21.09375 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "confidence", name: "Confidence", description: "Deal 20% more damage until your first miss each combat.", multiplier: 1.2, requiresNoPlayerMiss: true }] } },
  { id: "talent_99", name: "Weight of Frost", description: "Lose 10 Initiative. Your direct hits deal extra damage equal to 5% of your Armor, rounded up.", branch: "arcanist", kind: "passive", tier: 6, cost: 1, requires: ["talent_93"], position: { x: 32.19178082191781, y: 21.09375 }, icon: "✦", shape: "circle", combat: { passive: { initiative: -10, bonusDirectDamageFromArmorRatio: 0.05 } } },
  { id: "talent_100", name: "Thunderstorm", description: "Hit random enemies six times for 30% Magical Power as Lightning Damage. Hits against Electrified enemies deal 50% more damage.", branch: "arcanist", kind: "ability", tier: 7, cost: 1, requires: ["talent_91"], position: { x: 37.67123287671233, y: 15.625 }, icon: "✦", shape: "square", abilityId: "Thunderstorm" },
  { id: "talent_101", name: "Deep Freeze", description: "Deal 75% Magical Power as Frost Damage and apply Slowed. If the target is already Slowed, Stun it instead.", branch: "arcanist", kind: "ability", tier: 7, cost: 1, requires: ["talent_97"], position: { x: 29.45205479452055, y: 15.625 }, icon: "✦", shape: "square", abilityId: "DeepFreeze" },
  { id: "talent_102", name: "Arcane Overload", description: "Deal 50% Magical Power as Arcane Damage and apply 3 Arcane Wounds. Your next Arcane Blast against the target costs 0 Energy.", branch: "arcanist", kind: "ability", tier: 7, cost: 1, requires: ["talent_96"], position: { x: 25.34246575342466, y: 15.625 }, icon: "✦", shape: "square", abilityId: "ArcaneOverload" },
  { id: "talent_103", name: "Combustion", description: "Consume all Burn on the target and immediately deal its remaining damage. If this kills the target, spread half its Burn stacks to all other enemies before consuming them.", branch: "arcanist", kind: "ability", tier: 7, cost: 1, requires: ["talent_89"], position: { x: 17.123287671232877, y: 15.625 }, icon: "✦", shape: "square", abilityId: "Combustion" },
  { id: "talent_104", name: "Arcane Combustion", description: "Consume all Arcane Wounds on the target. Deal 50% Magical Power as Fire Damage per stack consumed and apply an equal number of Burn stacks.", branch: "arcanist", kind: "ability", tier: 7, cost: 1, requires: ["talent_89", "talent_96"], position: { x: 21.232876712328768, y: 15.625 }, icon: "✦", shape: "square", abilityId: "ArcaneCombustion" },
  { id: "talent_105", name: "Thundersnow", description: "Hit all enemies for 60% Magical Power as Frost and Lightning Damage. Apply Slowed to every target and Electrified to one random target.", branch: "arcanist", kind: "ability", tier: 7, cost: 1, requires: ["talent_91", "talent_97"], position: { x: 33.56164383561644, y: 15.625 }, icon: "✦", shape: "square", abilityId: "Thundersnow" },
  { id: "talent_106", name: "Arcane Knowledge", description: "+2 Intelligence. Each Arcane Wound increases Arcane Blast damage by 15% instead of 10%.", branch: "arcanist", kind: "passive", tier: 8, cost: 1, requires: ["talent_102"], position: { x: 25.34246575342466, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { passive: { stats: { intelligence: 2 } }, abilityModifiers: [{ id: "arcane-knowledge", name: "Arcane Knowledge", description: "Arcane Wounds grant Arcane Blast 5% additional damage per stack.", abilityIds: ["ArcaneBlast"], damagePerTargetStatusStackMultiplierDelta: 0.05, descriptionOverride: "Deal Arcane Damage equal to 20% of your Magical Power and apply 1 Arcane Wound. Each Arcane Wound increases Arcane Blast damage by 15%." }] } },
  { id: "talent_107", name: "Lower Temperature", description: "Frostbolt has a 50% chance to apply Frozen. Frozen prevents actions and breaks when damage is taken.", branch: "arcanist", kind: "passive", tier: 8, cost: 1, requires: ["talent_101"], position: { x: 29.45205479452055, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "lower-temperature", name: "Lower Temperature", description: "Frostbolt has a 50% chance to apply Frozen.", event: "on_hit", chance: 0.5, conditions: { abilityIds: ["Frostbolt"] }, effects: [{ type: "apply_status", status: createStatusEffect("frozen", { duration: 1 }), target: "target" }] }] } },
  { id: "talent_108", name: "Rain", description: "Thundersnow applies Wet to all enemies instead of Slowed.", branch: "arcanist", kind: "passive", tier: 8, cost: 1, requires: ["talent_105"], position: { x: 33.56164383561644, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "rain", name: "Rain", description: "Thundersnow applies Wet instead of Slowed.", abilityIds: ["Thundersnow"], replaceStatusApplication: { from: "slowed", to: "wet" }, descriptionOverride: "Hit all enemies for 60% Magical Power as Frost and Lightning Damage. Apply Wet to every target and Electrified to one random target." }] } },
  { id: "talent_109", name: "Intense Beam", description: "All four Lightning Beam hits strike the selected target.", branch: "arcanist", kind: "passive", tier: 8, cost: 1, requires: ["talent_100"], position: { x: 37.67123287671233, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "intense-beam", name: "Intense Beam", description: "All Lightning Beam hits strike the selected target.", abilityIds: ["LightningBeam"], randomTargetPerHit: false, descriptionOverride: "Strike the selected enemy four times for 20% Magical Power as Lightning Damage per hit. Each hit has a 20% chance to apply Electrified." }] } },
  { id: "talent_110", name: "Feedback", description: "+1 Energy gained at the start of your turn.", branch: "arcanist", kind: "passive", tier: 8, cost: 1, requires: ["talent_104"], position: { x: 21.232876712328768, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { passive: { energyRegen: 1 } } },
  { id: "talent_111", name: "Charring Fires", description: "Your Burn deals 10% more damage.", branch: "arcanist", kind: "passive", tier: 8, cost: 1, requires: ["talent_103"], position: { x: 17.123287671232877, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { passive: { statusDamage: { burn: 0.1 } } } },
  { id: "talent_112", name: "Self Immolation", description: "Apply 5 Burn to yourself and the selected enemy.", branch: "arcanist", kind: "ability", tier: 9, cost: 1, requires: ["talent_111"], position: { x: 17.123287671232877, y: 19.736842105263158 }, icon: "✦", shape: "square", abilityId: "SelfImmolation" },
  { id: "talent_113", name: "Arcane Barrier", description: "Gain Barrier equal to 50% of your Magical Power for 3 turns.", branch: "arcanist", kind: "ability", tier: 9, cost: 1, requires: ["talent_106", "talent_111"], position: { x: 21.232876712328768, y: 19.736842105263158 }, icon: "✦", shape: "square", abilityId: "ArcaneBarrier" },
  { id: "talent_114", name: "Frozen Path", description: "Gain 30% Dodge Chance for 3 turns. Dodge Chance cannot exceed 50%.", branch: "arcanist", kind: "ability", tier: 9, cost: 1, requires: ["talent_107", "talent_109"], position: { x: 33.56164383561644, y: 19.736842105263158 }, icon: "✦", shape: "square", abilityId: "FrozenPath" },
  { id: "talent_115", name: "Conductor", description: "Stun all enemies and yourself for 1 turn.", branch: "arcanist", kind: "ability", tier: 9, cost: 1, requires: ["talent_109"], position: { x: 37.67123287671233, y: 19.736842105263158 }, icon: "✦", shape: "square", abilityId: "Conductor" },
  { id: "talent_116", name: "Improved Barrier", description: "Arcane Barrier shields for 75% of your Magical Power instead of 50%.", branch: "arcanist", kind: "passive", tier: 10, cost: 1, requires: ["talent_113"], position: { x: 24.65753424657534, y: 19.736842105263158 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "improved-barrier", name: "Improved Barrier", description: "Arcane Barrier shields for 75% of Magical Power.", abilityIds: ["ArcaneBarrier"], statusStackPowerScaling: { power: "magical", scaling: 0.75 }, descriptionOverride: "Gain Barrier equal to 75% of your Magical Power for 3 turns." }] } },
  { id: "talent_117", name: "Reflective Barrier", description: "Enemies that damage your Barrier take damage equal to 20% of the damage absorbed by it.", branch: "arcanist", kind: "passive", tier: 11, cost: 1, requires: ["talent_116"], position: { x: 27.397260273972602, y: 21.710526315789476 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "reflective-barrier", name: "Reflective Barrier", description: "Reflect 20% of damage absorbed by Barrier.", event: "damage_taken", conditions: { absorbedByAnyStatus: ["barrier"] }, effects: [{ type: "damage", amount: 0, damageType: "arcane", target: "target", triggerDamageRatio: 0.2, triggerAbsorbedStatus: "barrier" }] }] } },
  { id: "talent_118", name: "Barbed Boots", description: "Frozen Path grants 40% Dodge Chance instead of 30%.", branch: "arcanist", kind: "passive", tier: 10, cost: 1, requires: ["talent_114"], position: { x: 30.136986301369863, y: 19.736842105263158 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "barbed-boots", name: "Barbed Boots", description: "Frozen Path grants 40% Dodge Chance.", abilityIds: ["FrozenPath"], statusMagnitude: 0.4, descriptionOverride: "Gain 40% Dodge Chance for 3 turns. Dodge Chance cannot exceed 50%." }] } },
  { id: "talent_119", name: "Ice Spikes", description: "Whenever an enemy misses you, it takes Frost Damage equal to 20% of your Magical Power.", branch: "arcanist", kind: "passive", tier: 11, cost: 1, requires: ["talent_118"], position: { x: 27.397260273972602, y: 17.763157894736842 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "ice-spikes", name: "Ice Spikes", description: "Enemies that miss take 20% Magical Power as Frost Damage.", event: "enemy_missed", effects: [{ type: "damage", amount: 0, damageType: "frost", scalingPower: "magical", scaling: 0.2, target: "target" }] }] } },
  { id: "talent_120", name: "Feel the Burn", description: "Self Immolation first restores Health equal to the remaining damage of the 5 Burn it applies to you.", branch: "arcanist", kind: "passive", tier: 10, cost: 1, requires: ["talent_112"], position: { x: 13.698630136986301, y: 19.736842105263158 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "feel-the-burn", name: "Feel the Burn", description: "Self Immolation heals before applying Burn.", abilityIds: ["SelfImmolation"], preHealSelfStatusRemainingDamage: "burn", descriptionOverride: "Restore Health equal to the full remaining damage of 5 Burn, then apply 5 Burn to yourself and the selected enemy." }] } },
  { id: "talent_121", name: "Refreshing Fires", description: "Self Immolation grants +2 Energy regeneration next turn.", branch: "arcanist", kind: "passive", tier: 11, cost: 1, requires: ["talent_120"], position: { x: 13.698630136986301, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "refreshing-fires", name: "Refreshing Fires", description: "Self Immolation grants +2 Energy regeneration next turn.", abilityIds: ["SelfImmolation"], nextTurnEnergyRegenBonus: 2, descriptionOverride: "Restore Health equal to the full remaining damage of 5 Burn, apply 5 Burn to yourself and the selected enemy, and gain +2 Energy regeneration next turn." }] } },
  { id: "talent_122", name: "Electrified Hug", description: "Conductor also applies Electrified to all enemies.", branch: "arcanist", kind: "passive", tier: 10, cost: 1, requires: ["talent_115"], position: { x: 41.0958904109589, y: 19.736842105263158 }, icon: "✦", shape: "circle", combat: { abilityModifiers: [{ id: "electrified-hug", name: "Electrified Hug", description: "Conductor also Electrifies all enemies.", abilityIds: ["Conductor"], additionalStatusApplications: [{ status: "electrified" }], descriptionOverride: "Stun all enemies and yourself for 1 turn, and apply Electrified to all enemies." }] } },
  { id: "talent_123", name: "Shell Shocked", description: "While Stunned, you take only 20% damage from all sources.", branch: "arcanist", kind: "passive", tier: 11, cost: 1, requires: ["talent_122"], position: { x: 41.0958904109589, y: 24.342105263157894 }, icon: "✦", shape: "circle", combat: { passive: { incomingDamageMultiplierWhileStunned: 0.2 } } },
  { id: "talent_124", name: "Blinding Light", description: "Whenever you apply Electrified to an enemy, it has a 20% chance, plus Luck's bonus to chance-based effects, to also become Blind.", branch: "arcanist", kind: "passive", tier: 10, cost: 1, requires: ["talent_115"], position: { x: 37.67123287671233, y: 15.131578947368421 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "blinding-light", name: "Blinding Light", description: "Applying Electrified has a 20% chance, plus Luck's bonus to chance-based effects, to also apply Blind.", event: "status_applied", chance: 0.2, conditions: { appliedAnyStatus: ["electrified"] }, effects: [{ type: "apply_status", status: createStatusEffect("blind"), target: "target" }] }] } },
  { id: "talent_127", name: "Pyromania", description: "While you are Burning, deal 10% more Arcane, Fire, Frost, and Lightning damage.", branch: "arcanist", kind: "passive", tier: 10, cost: 1, requires: ["talent_112"], position: { x: 17.123287671232877, y: 15.131578947368421 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "pyromania", name: "Pyromania", description: "Deal 10% more magical damage while Burning.", multiplier: 1.1, damageTypes: ["arcane", "fire", "frost", "lightning"], attackerHasAnyStatus: ["burn"] }] } },
  { id: "talent_128", name: "Living Furnace", description: "Your Burn deals 5% more damage to enemies while you are Burning.", branch: "arcanist", kind: "passive", tier: 11, cost: 1, requires: ["talent_127"], position: { x: 13.698630136986301, y: 15.131578947368421 }, icon: "✦", shape: "circle", combat: { statusDamageModifiers: [{ id: "living-furnace", name: "Living Furnace", description: "Burn deals 5% more damage to enemies while you are Burning.", statuses: ["burn"], sourceHasAnyStatus: ["burn"], bonus: 0.05 }] } },
  { id: "talent_129", name: "Greater Pyromania", description: "While you are Burning, deal an additional 10% more Arcane, Fire, Frost, and Lightning damage.", branch: "arcanist", kind: "passive", tier: 12, cost: 1, requires: ["talent_128"], position: { x: 10.273972602739725, y: 15.131578947368421 }, icon: "✦", shape: "circle", combat: { damageModifiers: [{ id: "greater-pyromania", name: "Greater Pyromania", description: "Deal an additional 10% more magical damage while Burning.", multiplier: 1.1, damageTypes: ["arcane", "fire", "frost", "lightning"], attackerHasAnyStatus: ["burn"] }] } },
  { id: "talent_130", name: "Greater Living Furnace", description: "Your Burn deals an additional 10% more damage to enemies while you are Burning.", branch: "arcanist", kind: "passive", tier: 13, cost: 1, requires: ["talent_129"], position: { x: 10.273972602739725, y: 19.736842105263158 }, icon: "✦", shape: "circle", combat: { statusDamageModifiers: [{ id: "greater-living-furnace", name: "Greater Living Furnace", description: "Burn deals an additional 10% more damage to enemies while you are Burning.", statuses: ["burn"], sourceHasAnyStatus: ["burn"], bonus: 0.1 }] } },
  { id: "talent_131", name: "Firestorm", description: "Deal 25% Magical Power as Fire Damage to all enemies, then apply 2 Burn to all enemies and yourself.", branch: "arcanist", kind: "ability", tier: 14, cost: 1, requires: ["talent_130"], position: { x: 10.273972602739725, y: 24.342105263157894 }, icon: "✦", shape: "square", abilityId: "Firestorm" },
  { id: "talent_132", name: "Heat Transfer", description: "Whenever Burn deals damage to you, restore 1 Energy.", branch: "arcanist", kind: "passive", tier: 15, cost: 1, requires: ["talent_131"], position: { x: 13.698630136986301, y: 28.289473684210524 }, icon: "✦", shape: "circle", combat: { triggers: [{ id: "heat-transfer", name: "Heat Transfer", description: "Burn damage restores 1 Energy.", event: "damage_taken", conditions: { minimumDamage: 1, sourceAnyStatus: ["burn"] }, effects: [{ type: "gain_energy", amount: 1, target: "self" }] }] } },
];

const TALENT_TREE_LAYOUT: Record<string, Talent["position"]> = {
  origin: { x: 27.397, y: 57.895 },
  brute_1: { x: 23.287, y: 57.895 },
  shadow_1: { x: 31.507, y: 57.895 },
  arcanist_1: { x: 27.397, y: 52.632 },
  talent_1: { x: 35.616, y: 57.895 },
  talent_2: { x: 39.04, y: 53.947 },
  talent_3: { x: 39.04, y: 61.843 },
  talent_4: { x: 42.466, y: 53.947 },
  talent_5: { x: 42.466, y: 61.843 },
  talent_6: { x: 42.466, y: 49.342 },
  talent_7: { x: 45.89, y: 53.947 },
  talent_8: { x: 42.466, y: 66.448 },
  talent_9: { x: 45.89, y: 61.843 },
  talent_10: { x: 49.315, y: 63.158 },
  talent_11: { x: 49.315, y: 52.632 },
  talent_12: { x: 45.89, y: 70.395 },
  talent_13: { x: 45.89, y: 45.395 },
  talent_14: { x: 49.315, y: 45.395 },
  talent_15: { x: 49.315, y: 71.053 },
  talent_16: { x: 52.74, y: 53.947 },
  talent_17: { x: 52.74, y: 61.843 },
  talent_18: { x: 52.74, y: 45.395 },
  talent_19: { x: 52.74, y: 70.395 },
  talent_20: { x: 56.164, y: 74.342 },
  talent_21: { x: 56.164, y: 66.448 },
  talent_22: { x: 56.164, y: 61.843 },
  talent_23: { x: 56.164, y: 49.342 },
  talent_24: { x: 56.164, y: 41.448 },
  talent_25: { x: 56.164, y: 53.947 },
  talent_26: { x: 59.589, y: 53.947 },
  talent_27: { x: 59.589, y: 61.843 },
  talent_28: { x: 59.589, y: 66.447 },
  talent_29: { x: 59.589, y: 49.342 },
  talent_30: { x: 49.315, y: 75 },
  talent_31: { x: 49.315, y: 40.79 },
  talent_32: { x: 59.589, y: 74.342 },
  talent_33: { x: 59.589, y: 41.448 },
  talent_34: { x: 49.315, y: 57.895 },
  talent_35: { x: 63.014, y: 74.342 },
  talent_36: { x: 63.014, y: 41.448 },
  talent_37: { x: 63.014, y: 57.895 },
  talent_38: { x: 39.041, y: 66.447 },
  talent_39: { x: 39.041, y: 49.342 },
  talent_40: { x: 66.438, y: 70.395 },
  talent_41: { x: 66.438, y: 45.395 },
  talent_42: { x: 66.438, y: 61.843 },
  talent_43: { x: 66.438, y: 53.948 },
  talent_44: { x: 45.89, y: 75 },
  talent_45: { x: 45.89, y: 40.79 },
  talent_46: { x: 45.89, y: 79.605 },
  talent_47: { x: 49.315, y: 79.605 },
  talent_48: { x: 42.466, y: 79.605 },
  talent_49: { x: 45.89, y: 84.211 },
  talent_50: { x: 45.89, y: 36.184 },
  talent_51: { x: 42.466, y: 36.184 },
  talent_52: { x: 49.315, y: 36.184 },
  talent_53: { x: 45.89, y: 31.579 },
  talent_54: { x: 66.438, y: 78.29 },
  talent_55: { x: 66.438, y: 37.5 },
  talent_56: { x: 69.863, y: 57.895 },
  talent_57: { x: 69.863, y: 66.447 },
  talent_58: { x: 69.863, y: 49.342 },
  talent_59: { x: 63.014, y: 49.342 },
  talent_60: { x: 63.014, y: 66.447 },
  talent_61: { x: 73.288, y: 57.895 },
  talent_62: { x: 73.288, y: 66.447 },
  talent_63: { x: 73.288, y: 49.342 },
  talent_64: { x: 76.712, y: 66.447 },
  talent_65: { x: 76.712, y: 57.895 },
  talent_66: { x: 76.712, y: 49.342 },
  talent_67: { x: 52.74, y: 40.79 },
  talent_68: { x: 52.74, y: 36.184 },
  talent_69: { x: 56.164, y: 36.184 },
  talent_70: { x: 59.589, y: 36.184 },
  talent_71: { x: 63.014, y: 36.184 },
  talent_72: { x: 52.74, y: 75 },
  talent_73: { x: 52.74, y: 79.605 },
  talent_74: { x: 56.164, y: 79.605 },
  talent_75: { x: 59.589, y: 79.605 },
  talent_76: { x: 63.014, y: 79.605 },
  talent_77: { x: 76.712, y: 44.737 },
  talent_78: { x: 76.712, y: 71.053 },
  talent_79: { x: 27.397, y: 46.711 },
  talent_80: { x: 29.452, y: 42.105 },
  talent_81: { x: 25.342, y: 42.105 },
  talent_82: { x: 21.233, y: 42.763 },
  talent_83: { x: 33.562, y: 42.763 },
  talent_84: { x: 18.493, y: 38.816 },
  talent_85: { x: 25.342, y: 37.5 },
  talent_86: { x: 29.452, y: 37.5 },
  talent_87: { x: 36.301, y: 38.816 },
  talent_88: { x: 15.753, y: 38.816 },
  talent_89: { x: 18.493, y: 34.868 },
  talent_90: { x: 39.041, y: 38.816 },
  talent_91: { x: 36.301, y: 34.868 },
  talent_92: { x: 22.603, y: 37.5 },
  talent_93: { x: 32.192, y: 37.5 },
  talent_94: { x: 15.753, y: 34.868 },
  talent_95: { x: 39.041, y: 34.868 },
  talent_96: { x: 25.342, y: 33.553 },
  talent_97: { x: 29.452, y: 33.553 },
  talent_98: { x: 22.603, y: 33.553 },
  talent_99: { x: 32.192, y: 33.553 },
  talent_100: { x: 37.671, y: 28.947 },
  talent_101: { x: 29.452, y: 28.947 },
  talent_102: { x: 25.342, y: 28.947 },
  talent_103: { x: 17.123, y: 28.947 },
  talent_104: { x: 21.233, y: 28.947 },
  talent_105: { x: 33.562, y: 28.947 },
  talent_106: { x: 25.3424657534247, y: 24.3421052631579 },
  talent_107: { x: 29.4520547945205, y: 24.3421052631579 },
  talent_108: { x: 33.5616438356164, y: 24.3421052631579 },
  talent_109: { x: 37.6712328767123, y: 24.3421052631579 },
  talent_110: { x: 21.2328767123288, y: 24.3421052631579 },
  talent_111: { x: 17.1232876712329, y: 24.3421052631579 },
  talent_112: { x: 17.1232876712329, y: 19.7368421052632 },
  talent_113: { x: 21.2328767123288, y: 19.7368421052632 },
  talent_114: { x: 33.5616438356164, y: 19.7368421052632 },
  talent_115: { x: 37.6712328767123, y: 19.7368421052632 },
  talent_116: { x: 24.6575342465753, y: 19.7368421052632 },
  talent_117: { x: 27.3972602739726, y: 21.7105263157895 },
  talent_118: { x: 30.1369863013699, y: 19.7368421052632 },
  talent_119: { x: 27.3972602739726, y: 17.7631578947368 },
  talent_120: { x: 13.6986301369863, y: 19.7368421052632 },
  talent_121: { x: 13.6986301369863, y: 24.3421052631579 },
  talent_122: { x: 41.0958904109589, y: 19.7368421052632 },
  talent_123: { x: 41.0958904109589, y: 24.3421052631579 },
  talent_124: { x: 37.67123287671233, y: 15.131578947368421 },
  talent_127: { x: 17.123287671232877, y: 15.131578947368421 },
  talent_128: { x: 13.698630136986301, y: 15.131578947368421 },
  talent_129: { x: 10.273972602739725, y: 15.131578947368421 },
  talent_130: { x: 10.273972602739725, y: 19.736842105263158 },
  talent_131: { x: 10.273972602739725, y: 24.342105263157894 },
  talent_132: { x: 13.698630136986301, y: 28.289473684210524 },
  cultist_1: { x: 27.397, y: 63.158 },
};

export const TALENTS: Talent[] = TALENT_NODES.map((talent) => {
  const positionedTalent = { ...talent, position: TALENT_TREE_LAYOUT[talent.id] ?? talent.position };
  const ability = talent.abilityId ? ABILITIES[talent.abilityId] : undefined;
  return ability ? {
    ...positionedTalent,
    abilityEnergyCost: ability.energyCost,
    abilityCooldownTurns: ability.cooldownTurns ?? 0,
  } : positionedTalent;
});

export const ENEMIES: Record<string, EnemyTemplate> = {
  dummy: { id: "dummy", name: "DUMMY", title: "Training Construct", maxHp: 100, power: 1, armor: 0, magicResistance: 0, hitChance: 0.95, dodgeChance: 0, damageType: "physical", energyCost: 1, intentText: "Training Strike · 1 damage", attackDescription: "A harmless training strike with 95% Hit Chance that deals 1 base Physical Damage. Costs 1 Energy.", accent: "#a8a69d" },
  ashHound: { id: "ashHound", name: "Ash Hound", title: "Feral Beast", maxHp: 28, power: 7, armor: 1, magicResistance: 0, hitChance: 0.95, dodgeChance: 0.08, damageType: "physical", energyCost: 3, intentText: "Raking Claws · 7 damage", attackDescription: "Rakes the target with ash-caked claws. Costs 3 Energy and applies Bleed when it deals damage.", onHitEffect: "bleed", accent: "#d47a43" },
  cinderCultist: { id: "cinderCultist", name: "Cinder Cultist", title: "Fanatic", maxHp: 34, power: 9, armor: 2, magicResistance: 2, hitChance: 0.96, dodgeChance: 0.03, damageType: "arcane", energyCost: 4, intentText: "Searing Brand · 9 damage", attackDescription: "Brands the target with a searing sigil. Costs 4 Energy.", accent: "#a46ad4" },
  emberWisp: { id: "emberWisp", name: "Ember Wisp", title: "Restless Flame", maxHp: 22, power: 6, armor: 0, magicResistance: 3, hitChance: 0.98, dodgeChance: 0.12, damageType: "arcane", energyCost: 3, intentText: "Scorch · 6 damage", attackDescription: "Releases a focused burst of living flame. Costs 3 Energy.", accent: "#d6ad53" },
  ashenWarden: { id: "ashenWarden", name: "The Ashen Warden", title: "Keeper of the Black Gate", maxHp: 92, power: 12, armor: 4, magicResistance: 4, hitChance: 1, dodgeChance: 0.05, damageType: "physical", energyCost: 5, intentText: "Cinder Cleave · 12 damage", attackDescription: "Sweeps a burning blade across the battlefield. Costs 5 Energy.", accent: "#de5b47" },
};

export const ITEMS: GearItem[] = [
  { id: "ironCleaver", name: "Notched Iron Cleaver", slot: "mainHand", weaponEquipType: "oneHand", weaponKind: "axe", rarity: "uncommon", description: "Still sharp enough to draw blood.", stats: { strength: 2 }, physicalPower: 3, set: "ashborn", setName: "Ashborn Warplate" },
  { id: "embershard", name: "Embershard Focus", slot: "offHand", weaponEquipType: "offHand", weaponKind: "tome", rarity: "rare", description: "Warm whispers curl around the crystal.", stats: { intelligence: 3 }, magicalPower: 2 },
  { id: "wandererHood", name: "Wanderer's Hood", slot: "head", armorMaterial: "leather", rarity: "common", description: "A little anonymity goes a long way.", stats: { agility: 1 }, armor: 1 },
  { id: "ashCuirass", name: "Ashborn Cuirass", slot: "chest", armorMaterial: "plate", rarity: "rare", description: "Forged in a fire that never cooled.", stats: { strength: 2, vitality: 2 }, armor: 5, set: "ashborn", setName: "Ashborn Warplate" },
  { id: "veilTrousers", name: "Veilwalker Trousers", slot: "pants", armorMaterial: "leather", rarity: "uncommon", description: "They leave no footprint in soot.", stats: { agility: 2 }, armor: 2, set: "veilwalker", setName: "Veilwalker's Guile" },
  { id: "roadBoots", name: "Dustworn Boots", slot: "boots", armorMaterial: "leather", rarity: "common", description: "Made for roads best left unnamed.", stats: { vitality: 1 }, armor: 1 },
  { id: "garnetBand", name: "Garnet Signet", slot: "ring", rarity: "rare", description: "A noble crest has been scratched away.", stats: { strength: 1, luck: 2 } },
  { id: "moonRing", name: "Moonlit Coil", slot: "ring", rarity: "epic", description: "Its silver surface reflects an unfamiliar sky.", stats: { intelligence: 2, agility: 1, luck: 1 } },
  { id: "wardenHelm", name: "Warden's Broken Crown", slot: "head", armorMaterial: "plate", rarity: "epic", description: "The last ember still burns within.", stats: { vitality: 3, strength: 2 }, armor: 4, set: "ashborn", setName: "Ashborn Warplate" },
  { id: "seerCowl", name: "Cowl of Quiet Sparks", slot: "head", armorMaterial: "cloth", rarity: "uncommon", description: "Tiny runes brighten whenever danger draws near.", stats: { intelligence: 2 }, magicResistance: 2 },
  { id: "nightstitchVest", name: "Nightstitch Vest", slot: "chest", armorMaterial: "leather", rarity: "uncommon", description: "Supple leather sewn for swift, silent movement.", stats: { agility: 2, vitality: 1 }, armor: 3 },
  { id: "emberweaveRobe", name: "Emberweave Robe", slot: "chest", armorMaterial: "cloth", rarity: "rare", description: "Warm threads carry old protective sigils.", stats: { intelligence: 3 }, armor: 1, magicResistance: 4 },
  { id: "ashboundLegguards", name: "Ashbound Legguards", slot: "pants", armorMaterial: "plate", rarity: "rare", description: "Blackened plates that still hold the Warden's heat.", stats: { strength: 1, vitality: 2 }, armor: 4, set: "ashborn", setName: "Ashborn Warplate" },
  { id: "runeclothLegwraps", name: "Runecloth Legwraps", slot: "pants", armorMaterial: "cloth", rarity: "uncommon", description: "Loose-woven cloth marked with patient warding ink.", stats: { intelligence: 2, luck: 1 }, magicResistance: 2 },
  { id: "ironmarchSabatons", name: "Ironmarch Sabatons", slot: "boots", armorMaterial: "plate", rarity: "rare", description: "Every heavy step sounds like a closing gate.", stats: { strength: 1, vitality: 2 }, armor: 4 },
  { id: "softstepSlippers", name: "Softstep Slippers", slot: "boots", armorMaterial: "cloth", rarity: "uncommon", description: "Enchanted soles soften even a hurried retreat.", stats: { agility: 2, intelligence: 1 }, magicResistance: 1 },
  { id: "copperLoop", name: "Wayfarer's Copper Loop", slot: "ring", rarity: "common", description: "A plain ring polished smooth by years on the road.", stats: { vitality: 1, luck: 1 } },
  { id: "wardenShortsword", name: "Warden's Shortsword", slot: "mainHand", weaponEquipType: "mainHand", weaponKind: "sword", rarity: "uncommon", description: "A disciplined blade balanced for the dominant hand.", stats: { strength: 2 }, physicalPower: 4 },
  { id: "pilgrimMace", name: "Cinder Pilgrim's Mace", slot: "mainHand", weaponEquipType: "mainHand", weaponKind: "mace", rarity: "rare", description: "Its scorched head rewards deliberate, crushing blows.", stats: { strength: 3, vitality: 1 }, physicalPower: 5 },
  { id: "veilDagger", name: "Veilglass Dagger", slot: "mainHand", weaponEquipType: "oneHand", weaponKind: "dagger", rarity: "rare", description: "A thin edge suited to either hand.", stats: { agility: 3 }, physicalPower: 3 },
  { id: "ashWand", name: "Ashen Conduit", slot: "mainHand", weaponEquipType: "oneHand", weaponKind: "wand", rarity: "epic", description: "A charred wand that focuses heat into precise sigils.", stats: { intelligence: 3, luck: 1 }, magicalPower: 5 },
  { id: "gateShield", name: "Black Gate Buckler", slot: "offHand", weaponEquipType: "offHand", weaponKind: "shield", rarity: "uncommon", description: "A compact shield scarred by countless claws.", stats: { vitality: 2 }, armor: 3 },
  { id: "greatsword", name: "Roadcleaver Greatsword", slot: "mainHand", weaponEquipType: "twoHand", weaponKind: "sword", rarity: "rare", description: "A broad blade that leaves no hand free for defense.", stats: { strength: 4 }, physicalPower: 7 },
  { id: "greataxe", name: "Ashfall Greataxe", slot: "mainHand", weaponEquipType: "twoHand", weaponKind: "axe", rarity: "epic", description: "Its crescent edge falls with the weight of a burned oak.", stats: { strength: 5, vitality: 1 }, physicalPower: 8 },
  { id: "greatmace", name: "Gatebreaker Maul", slot: "mainHand", weaponEquipType: "twoHand", weaponKind: "mace", rarity: "rare", description: "Built to turn armor, stone, and bone into rubble.", stats: { strength: 4, vitality: 2 }, physicalPower: 7 },
  { id: "emberstaff", name: "Embercaller's Staff", slot: "mainHand", weaponEquipType: "twoHand", weaponKind: "staff", rarity: "epic", description: "A living coal glows between its forked branches.", stats: { intelligence: 5 }, magicalPower: 8 },
  { id: "cinderPolearm", name: "Cinderwatch Polearm", slot: "mainHand", weaponEquipType: "twoHand", weaponKind: "polearm", rarity: "rare", description: "Long reach keeps the ash-born at a cautious distance.", stats: { strength: 2, agility: 3 }, physicalPower: 7 },
];

export const GEAR_SET_BONUSES: GearSetBonusDefinition[] = [
  {
    setId: "ashborn",
    setName: "Ashborn Warplate",
    requiredPieces: 2,
    description: "+2 Strength.",
    passive: { stats: { strength: 2 } },
  },
  {
    setId: "ashborn",
    setName: "Ashborn Warplate",
    requiredPieces: 3,
    description: "Bleed only deals half damage to you.",
    passive: { bleedDamageReduction: 0.5 },
  },
  {
    setId: "ashborn",
    setName: "Ashborn Warplate",
    requiredPieces: 4,
    description: "+3 Vitality.",
    passive: { stats: { vitality: 3 } },
  },
];

export const ADVENTURE: AdventureNode[] = [
  { id: "road", type: "combat", eyebrow: "Encounter I", title: "Smoke on the Road", description: "Two shapes stalk through the drifting ash. They have already caught your scent.", enemies: ["ashHound", "ashHound"], reward: { experience: 55, gold: 9, loot: true } },
  { id: "shrine", type: "event", eyebrow: "Unknown Event", title: "The Forgotten Shrine", description: "A cracked idol watches over a bowl of cold embers. Something valuable may still answer a prayer." },
  { id: "pilgrims", type: "combat", eyebrow: "Encounter II", title: "The Charred Pilgrims", description: "A fanatic raises their torch as a living flame coils at their shoulder.", enemies: ["cinderCultist", "emberWisp"], reward: { experience: 75, gold: 14, loot: true } },
  { id: "gate", type: "boss", eyebrow: "Boss Encounter", title: "The Black Gate", description: "The Warden rises from its throne. Iron groans, and the road behind you disappears.", enemies: ["ashenWarden"], reward: { experience: 125, gold: 32, loot: true } },
];

export const ENDLESS_ADVENTURE: AdventureNode = {
  id: "shadow-proving-grounds",
  type: "combat",
  eyebrow: "Endless Training",
  title: "Shadow Proving Grounds",
  description: "Test your Shadow build against an endless sequence of training constructs.",
  enemies: ["dummy", "dummy"],
};
