export const ITEM_ICON_URLS: Record<string, string> = {
  "consumable-ms0e3hjh-5bewd": "/assets/items/yumberries.webp",
  "consumable-ms0e551z-v6qcf": "/assets/items/minor-healing-potion.webp",
  "gear-ms0h89t2-sczql": "/assets/items/windsong-staff.webp",
  "gear-ms0h9jvh-cpg4y": "/assets/items/windsong-sword.webp",
  "gear-ms0haj6d-e8pmv": "/assets/items/windsong-dagger.webp",
  "gear-ms0hb5cw-j14wj": "/assets/items/dusty-cowl.webp",
  "gear-ms0hdxb1-bxamd": "/assets/items/dusty-boots.webp",
  "gear-ms0hf0m3-j3pcx": "/assets/items/old-armor.webp",
  "gear-ms0hfvkg-yni9w": "/assets/items/old-leather-pants.webp",
  "gear-ms0hgg09-w6afk": "/assets/items/old-robes.webp",
  "consumable-ms0ifcle-isww5": "/assets/items/small-bloodberry.webp",
  "item-ms0jd8ky-lu2zb": "/assets/items/fur.webp",
  "item-ms0jdzsp-pnyoa": "/assets/items/wolf-fang.webp",
  "item-ms0jej41-7sii2": "/assets/items/rats-tail.webp",
  "item-ms0jf0sp-z8hcl": "/assets/items/wisp-essence.webp",
  "item-ms0jgblm-ko16i": "/assets/items/bear-claw.webp",
  "gear-ms0l8elz-4jlgf": "/assets/items/mystical-ring.webp",
  "item-ms0ss0dt-z4bke": "/assets/items/metal-scrap.webp",
  "gear-ms0svay5-evj17": "/assets/gear-icons/head-01.webp",
  "gear-ms0sx064-zq3n5": "/assets/gear-icons/chest-01.webp",
  "gear-ms0syhpj-m13xr": "/assets/gear-icons/boots-01.webp",
  "gear-ms0t0crb-p4hdm": "/assets/gear-icons/pants-01.webp",
  "gear-ms1i1671-yxsnp": "/assets/gear-icons/head-leather.webp",
  "gear-ms1i5k37-1rg9d": "/assets/gear-icons/boots-02.webp",
  "gear-ms1i77n7-j9o2s": "/assets/gear-icons/chest-02.webp",
  "gear-ms1iadb1-2snx8": "/assets/gear-icons/chest-cloth.webp",
  "gear-ms1iccqm-4yu0n": "/assets/gear-icons/head-cloth.webp",
  "gear-ms1id4sv-l0ihy": "/assets/gear-icons/twohand-staff.webp",
  "item-ms1if1q6-746wi": "/assets/items/fine-cloth.webp",
  "item-ms1igebd-dlhst": "/assets/items/spider-silk.webp",
  "gear-ms27lxuu-3o5xy": "/assets/gear-icons/head.webp",
  "gear-ms27p0je-if2hq": "/assets/gear-icons/chest.webp",
  "gear-ms27upmg-hxmuw": "/assets/gear-icons/boots-plate.webp",
  "gear-ms280r0n-f50t1": "/assets/gear-icons/sword-01.webp",
  "gear-ms281ud7-6ch5q": "/assets/gear-icons/main-dagger.webp",
  "gear-ms282mba-u9w1d": "/assets/gear-icons/shield-04.webp",
  "gear-ms285m4c-ripkk": "/assets/gear-icons/staff-01.webp",
  "gear-ms287a86-1kp9c": "/assets/gear-icons/twohand-axe.webp",
  "gear-ms288urw-5g9j1": "/assets/gear-icons/chest-leather.webp",
  "gear-ms28b6ae-at7dk": "/assets/gear-icons/head-leather.webp",
  "gear-ms28cwtb-huihn": "/assets/gear-icons/pants-leather.webp",
  "gear-ms28fdzv-vc0os": "/assets/gear-icons/boots-02.webp",
  "consumable-ms28qbji-u8z5k": "/assets/items/moonpetal.webp",
  "consumable-ms28tk3f-40hgi": "/assets/items/glowcap-mushrooms.webp",
  "consumable-ms28u8bo-5u249": "/assets/items/empty-alchemy-vial.webp",
  "gear-ms28xiyy-mjgo3": "/assets/gear-icons/head-leather.webp",
  "gear-ms28zlur-cywng": "/assets/gear-icons/pants-leather.webp",
  "consumable-ms2v69ag-xp79t": "/assets/items/potion-red-normal.webp",
  "consumable-ms2v7x2f-ahbvt": "/assets/items/potion-green-minor.webp",
  "consumable-ms2vc57w-fbqi2": "/assets/items/potion-purple-minor.webp",
  "consumable-ms2vf476-12fhj": "/assets/items/minor-healing-potion.webp",
  "consumable-ms2vgbcc-5hb8n": "/assets/items/potion-purple-greater.webp",
  "gear-nightveil-cowl": "/assets/gear-icons/head-03.webp",
  "gear-nightveil-jerkin": "/assets/gear-icons/chest-03.webp",
  "gear-nightveil-legwraps": "/assets/gear-icons/pants-03.webp",
  "gear-nightveil-treads": "/assets/gear-icons/boots-03.webp",
  "gear-trollforged-greathelm": "/assets/gear-icons/head-04.webp",
  "gear-trollforged-breastplate": "/assets/gear-icons/chest-04.webp",
  "gear-trollforged-legguards": "/assets/gear-icons/pants-04.webp",
  "gear-trollforged-warboots": "/assets/gear-icons/boots-04.webp",
  "gear-runewoven-cowl": "/assets/gear-icons/head-05.webp",
  "gear-runewoven-robes": "/assets/gear-icons/chest-05.webp",
  "gear-runewoven-leggings": "/assets/gear-icons/pants-05.webp",
  "gear-runewoven-boots": "/assets/gear-icons/boots-05.webp",
  "gear-ms30095w-ci3mw": "/assets/gear-icons/twohand-polearm.webp",
  "gear-ms3054kn-cs3uu": "/assets/gear-icons/dagger-01.webp",
  "gear-ms307fr5-vebz0": "/assets/gear-icons/staff-01.webp",
  "item-highfall-frostroot": "/assets/items/moonpetal.webp",
  "consumable-highfall-restorative": "/assets/items/potion-red-greater.webp",
  "consumable-stonebloom-draught": "/assets/items/potion-green-normal.webp",
  "gear-cairnkeepers-loop": "/assets/gear-icons/ring-04.webp",
  "gear-windsong-thornbark-visor": "/assets/gear-icons/head-02.webp",
  "gear-windsong-thornbark-buckler": "/assets/gear-icons/shield-02.webp",
  "gear-windsong-galehide-jerkin": "/assets/gear-icons/chest-03.webp",
  "gear-windsong-galehide-striders": "/assets/gear-icons/boots-03.webp",
  "gear-windsong-wispwoven-leggings": "/assets/gear-icons/pants-02.webp",
  "gear-windsong-wispwoven-band": "/assets/gear-icons/ring-02.webp",
  "gear-windsong-bramblefang": "/assets/gear-icons/sword-02.webp",
  "gear-windsong-moondrop-wand": "/assets/gear-icons/wand-02.webp",
  "gear-windsong-wolfstep-loop": "/assets/gear-icons/ring-03.webp",
  "consumable-windsong-whisperbloom-tonic": "/assets/items/potion-blue-minor.webp",
};

export const CRAFTING_MATERIAL_ARTWORK_URLS = [
  "/assets/items/metal-scrap.webp",
  "/assets/items/iron-ore.webp",
  "/assets/items/copper-ore.webp",
  "/assets/items/silver-ore.webp",
  "/assets/items/gold-ore.webp",
  "/assets/items/coal.webp",
  "/assets/items/hardwood.webp",
  "/assets/items/ancient-bark.webp",
  "/assets/items/tanned-leather.webp",
  "/assets/items/fine-cloth.webp",
  "/assets/items/spider-silk.webp",
  "/assets/items/arcane-crystal.webp",
  "/assets/items/frost-shard.webp",
  "/assets/items/ember-core.webp",
  "/assets/items/storm-essence.webp",
  "/assets/items/poison-gland.webp",
  "/assets/items/bone-fragments.webp",
  "/assets/items/monster-hide.webp",
  "/assets/items/moonpetal.webp",
  "/assets/items/glowcap-mushrooms.webp",
  "/assets/items/empty-alchemy-vial.webp",
] as const;

export const CONSUMABLE_POTION_ARTWORK_URLS = [
  "/assets/items/minor-healing-potion.webp",
  "/assets/items/potion-red-normal.webp",
  "/assets/items/potion-red-greater.webp",
  "/assets/items/potion-red-major.webp",
  "/assets/items/potion-red-superior.webp",
  "/assets/items/potion-blue-minor.webp",
  "/assets/items/potion-blue-normal.webp",
  "/assets/items/potion-blue-greater.webp",
  "/assets/items/potion-blue-major.webp",
  "/assets/items/potion-blue-superior.webp",
  "/assets/items/potion-green-minor.webp",
  "/assets/items/potion-green-normal.webp",
  "/assets/items/potion-green-greater.webp",
  "/assets/items/potion-green-major.webp",
  "/assets/items/potion-green-superior.webp",
  "/assets/items/potion-purple-minor.webp",
  "/assets/items/potion-purple-normal.webp",
  "/assets/items/potion-purple-greater.webp",
  "/assets/items/potion-purple-major.webp",
  "/assets/items/potion-purple-superior.webp",
] as const;

export const ITEM_ARTWORK_URLS = [...new Set([
  ...Object.values(ITEM_ICON_URLS).filter((url) => url.startsWith("/assets/items/")),
  ...CONSUMABLE_POTION_ARTWORK_URLS,
  ...CRAFTING_MATERIAL_ARTWORK_URLS,
])];

export function getItemIconUrl(itemId: string): string | undefined {
  return ITEM_ICON_URLS[itemId];
}
