export const ITEM_ICON_URLS: Record<string, string> = {
  "consumable-ms0e3hjh-5bewd": "/assets/items/yumberries.webp",
  "consumable-ms0e551z-v6qcf": "/assets/items/minor-healing-potion.webp",
  "gear-ms0h89t2-sczql": "/assets/items/windsong-staff.webp",
  "gear-ms0h9jvh-cpg4y": "/assets/items/windsong-sword.webp",
  "gear-ms0haj6d-e8pmv": "/assets/items/windsong-dagger.webp",
  "gear-ms0hb5cw-j14wj": "/assets/items/dusty-cowl.webp",
  "gear-ms0hdxb1-bxamd": "/assets/items/dusty-boots.webp",
  "gear-ms0hf0m3-j3pcx": "/assets/items/old-armor.webp",
  "gear-ms0hfvkg-yni9w": "/assets/items/old-leather-pants.webp",
  "gear-ms0hgg09-w6afk": "/assets/items/old-robes.webp",
  "consumable-ms0ifcle-isww5": "/assets/items/small-bloodberry.webp",
  "item-ms0jd8ky-lu2zb": "/assets/items/fur.webp",
  "item-ms0jdzsp-pnyoa": "/assets/items/wolf-fang.webp",
  "item-ms0jej41-7sii2": "/assets/items/rats-tail.webp",
  "item-ms0jf0sp-z8hcl": "/assets/items/wisp-essence.webp",
  "item-ms0jgblm-ko16i": "/assets/items/bear-claw.webp",
  "gear-ms0l8elz-4jlgf": "/assets/items/mystical-ring.webp",
  "item-ms0ss0dt-z4bke": "/assets/items/metal-scrap.webp",
  "gear-ms0svay5-evj17": "/assets/gear-icons/head-01.webp",
  "gear-ms0sx064-zq3n5": "/assets/gear-icons/chest-01.webp",
  "gear-ms0syhpj-m13xr": "/assets/gear-icons/boots-01.webp",
  "gear-ms0t0crb-p4hdm": "/assets/gear-icons/pants-01.webp",
  "gear-ms1i1671-yxsnp": "/assets/gear-icons/head-leather.webp",
  "gear-ms1i5k37-1rg9d": "/assets/gear-icons/boots-02.webp",
  "gear-ms1i77n7-j9o2s": "/assets/gear-icons/chest-02.webp",
  "gear-ms1iadb1-2snx8": "/assets/gear-icons/chest-cloth.webp",
  "gear-ms1iccqm-4yu0n": "/assets/gear-icons/head-cloth.webp",
  "gear-ms1id4sv-l0ihy": "/assets/gear-icons/twohand-staff.webp",
  "item-ms1if1q6-746wi": "/assets/items/fine-cloth.webp",
  "item-ms1igebd-dlhst": "/assets/items/spider-silk.webp",
  "gear-ms27lxuu-3o5xy": "/assets/gear-icons/head.webp",
  "gear-ms27p0je-if2hq": "/assets/gear-icons/chest.webp",
  "gear-ms27upmg-hxmuw": "/assets/gear-icons/boots-plate.webp",
  "gear-ms280r0n-f50t1": "/assets/gear-icons/sword-01.webp",
  "gear-ms281ud7-6ch5q": "/assets/gear-icons/main-dagger.webp",
  "gear-ms282mba-u9w1d": "/assets/gear-icons/shield-04.webp",
  "gear-ms285m4c-ripkk": "/assets/gear-icons/staff-01.webp",
  "gear-ms287a86-1kp9c": "/assets/gear-icons/twohand-axe.webp",
  "gear-ms288urw-5g9j1": "/assets/gear-icons/chest-leather.webp",
  "gear-ms28b6ae-at7dk": "/assets/gear-icons/head-leather.webp",
  "gear-ms28cwtb-huihn": "/assets/gear-icons/pants-leather.webp",
  "gear-ms28fdzv-vc0os": "/assets/gear-icons/boots-02.webp",
  "consumable-ms28qbji-u8z5k": "/assets/items/moonpetal.webp",
  "consumable-ms28tk3f-40hgi": "/assets/items/glowcap-mushrooms.webp",
  "consumable-ms28u8bo-5u249": "/assets/items/empty-alchemy-vial.webp",
  "gear-ms28xiyy-mjgo3": "/assets/gear-icons/head-leather.webp",
  "gear-ms28zlur-cywng": "/assets/gear-icons/pants-leather.webp",
  "consumable-ms2v69ag-xp79t": "/assets/items/potion-red-normal.webp",
  "consumable-ms2v7x2f-ahbvt": "/assets/items/potion-green-minor.webp",
  "consumable-ms2vc57w-fbqi2": "/assets/items/potion-purple-minor.webp",
  "consumable-ms2vf476-12fhj": "/assets/items/minor-healing-potion.webp",
  "consumable-ms2vgbcc-5hb8n": "/assets/items/potion-purple-greater.webp",
  "gear-nightveil-cowl": "/assets/gear-icons/head-03.webp",
  "gear-nightveil-jerkin": "/assets/gear-icons/chest-03.webp",
  "gear-nightveil-legwraps": "/assets/gear-icons/pants-03.webp",
  "gear-nightveil-treads": "/assets/gear-icons/boots-03.webp",
  "gear-trollforged-greathelm": "/assets/gear-icons/head-04.webp",
  "gear-trollforged-breastplate": "/assets/gear-icons/chest-04.webp",
  "gear-trollforged-legguards": "/assets/gear-icons/pants-04.webp",
  "gear-trollforged-warboots": "/assets/gear-icons/boots-04.webp",
  "gear-runewoven-cowl": "/assets/gear-icons/head-05.webp",
  "gear-runewoven-robes": "/assets/gear-icons/chest-05.webp",
  "gear-runewoven-leggings": "/assets/gear-icons/pants-05.webp",
  "gear-runewoven-boots": "/assets/gear-icons/boots-05.webp",
  "gear-ms30095w-ci3mw": "/assets/gear-icons/twohand-polearm.webp",
  "gear-ms3054kn-cs3uu": "/assets/gear-icons/dagger-01.webp",
  "gear-ms307fr5-vebz0": "/assets/gear-icons/staff-01.webp",
  "item-highfall-frostroot": "/assets/items/moonpetal.webp",
  "consumable-highfall-restorative": "/assets/items/potion-red-greater.webp",
  "consumable-stonebloom-draught": "/assets/items/potion-green-normal.webp",
  "gear-cairnkeepers-loop": "/assets/gear-icons/ring-04.webp",
  "gear-windsong-thornbark-visor": "/assets/gear-icons/head-02.webp",
  "gear-windsong-thornbark-buckler": "/assets/gear-icons/shield-02.webp",
  "gear-windsong-galehide-jerkin": "/assets/gear-icons/chest-03.webp",
  "gear-windsong-galehide-striders": "/assets/gear-icons/boots-03.webp",
  "gear-windsong-wispwoven-leggings": "/assets/gear-icons/pants-02.webp",
  "gear-windsong-wispwoven-band": "/assets/gear-icons/ring-02.webp",
  "gear-windsong-bramblefang": "/assets/gear-icons/sword-02.webp",
  "gear-windsong-moondrop-wand": "/assets/gear-icons/wand-02.webp",
  "gear-windsong-wolfstep-loop": "/assets/gear-icons/ring-03.webp",
  "consumable-windsong-whisperbloom-tonic": "/assets/items/potion-blue-minor.webp",
  "item-a4-bog-iron": "/assets/items/iron-ore.webp",
  "item-a4-venom-sac": "/assets/items/poison-gland.webp",
  "item-a4-mire-reed": "/assets/items/moonpetal.webp",
  "gear-a4-fenwarden-head": "/assets/gear-icons/head-01.webp",
  "gear-a4-fenwarden-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a4-fenwarden-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a4-fenwarden-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a4-fenwarden-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a4-mirestalker-head": "/assets/gear-icons/head-02.webp",
  "gear-a4-mirestalker-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a4-mirestalker-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a4-mirestalker-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a4-mirestalker-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a4-bogcleaver": "/assets/gear-icons/axe-05.webp",
  "gear-a4-witchlight-wand": "/assets/gear-icons/wand-01.webp",
  "item-a5-cindersteel": "/assets/items/copper-ore.webp",
  "item-a5-ember-fragment": "/assets/items/ember-core.webp",
  "item-a5-sootweave": "/assets/items/fine-cloth.webp",
  "gear-a5-emberforged-head": "/assets/gear-icons/head-01.webp",
  "gear-a5-emberforged-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a5-emberforged-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a5-emberforged-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a5-emberforged-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a5-cinderweave-head": "/assets/gear-icons/head-02.webp",
  "gear-a5-cinderweave-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a5-cinderweave-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a5-cinderweave-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a5-cinderweave-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a5-foundry-maul": "/assets/gear-icons/mace-01.webp",
  "gear-a5-cinderbrand": "/assets/gear-icons/sword-02.webp",
  "item-a6-abyssal-pearl": "/assets/items/arcane-crystal.webp",
  "item-a6-relic-shard": "/assets/items/bone-fragments.webp",
  "item-a6-tideglass": "/assets/items/frost-shard.webp",
  "gear-a6-depthguard-head": "/assets/gear-icons/head-01.webp",
  "gear-a6-depthguard-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a6-depthguard-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a6-depthguard-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a6-depthguard-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a6-tidecaller-head": "/assets/gear-icons/head-02.webp",
  "gear-a6-tidecaller-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a6-tidecaller-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a6-tidecaller-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a6-tidecaller-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a6-tidebreaker": "/assets/gear-icons/polearm-02.webp",
  "gear-a6-oracle-tome": "/assets/gear-icons/tome-03.webp",
  "item-a7-nightglass": "/assets/items/arcane-crystal.webp",
  "item-a7-umbral-silk": "/assets/items/spider-silk.webp",
  "item-a7-bloodstone": "/assets/items/gold-ore.webp",
  "gear-a7-nightglass-head": "/assets/gear-icons/head-01.webp",
  "gear-a7-nightglass-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a7-nightglass-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a7-nightglass-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a7-nightglass-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a7-bloodbound-head": "/assets/gear-icons/head-02.webp",
  "gear-a7-bloodbound-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a7-bloodbound-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a7-bloodbound-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a7-bloodbound-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a7-mirrorfang": "/assets/gear-icons/dagger-03.webp",
  "gear-a7-eclipse-staff": "/assets/gear-icons/staff-04.webp",
  "item-a8-rimebone": "/assets/items/bone-fragments.webp",
  "item-a8-frostheart": "/assets/items/frost-shard.webp",
  "item-a8-white-pelt": "/assets/items/fur.webp",
  "gear-a8-rimeguard-head": "/assets/gear-icons/head-01.webp",
  "gear-a8-rimeguard-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a8-rimeguard-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a8-rimeguard-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a8-rimeguard-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a8-winterweave-head": "/assets/gear-icons/head-02.webp",
  "gear-a8-winterweave-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a8-winterweave-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a8-winterweave-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a8-winterweave-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a8-white-maw-axe": "/assets/gear-icons/axe-04.webp",
  "gear-a8-aurora-wand": "/assets/gear-icons/wand-05.webp",
  "item-a9-skyiron": "/assets/items/silver-ore.webp",
  "item-a9-storm-core": "/assets/items/storm-essence.webp",
  "item-a9-cloudfeather": "/assets/items/fine-cloth.webp",
  "gear-a9-stormrunner-head": "/assets/gear-icons/head-01.webp",
  "gear-a9-stormrunner-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a9-stormrunner-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a9-stormrunner-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a9-stormrunner-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a9-tempest-sage-head": "/assets/gear-icons/head-02.webp",
  "gear-a9-tempest-sage-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a9-tempest-sage-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a9-tempest-sage-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a9-tempest-sage-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a9-skybreaker": "/assets/gear-icons/polearm-05.webp",
  "gear-a9-stormcallers-tome": "/assets/gear-icons/tome-01.webp",
  "item-a10-hollowsteel": "/assets/items/gold-ore.webp",
  "item-a10-crown-shard": "/assets/items/arcane-crystal.webp",
  "item-a10-soul-ash": "/assets/items/coal.webp",
  "gear-a10-crownless-head": "/assets/gear-icons/head-01.webp",
  "gear-a10-crownless-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a10-crownless-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a10-crownless-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a10-crownless-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a10-veilborn-head": "/assets/gear-icons/head-02.webp",
  "gear-a10-veilborn-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a10-veilborn-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a10-veilborn-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a10-veilborn-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a10-ashen-oracle-head": "/assets/gear-icons/head-03.webp",
  "gear-a10-ashen-oracle-chest": "/assets/gear-icons/chest-04.webp",
  "gear-a10-ashen-oracle-pants": "/assets/gear-icons/pants-05.webp",
  "gear-a10-ashen-oracle-boots": "/assets/gear-icons/boots-01.webp",
  "gear-a10-ashen-oracle-ring": "/assets/gear-icons/ring-02.webp",
  "gear-a10-crown-sunder": "/assets/gear-icons/sword-01.webp",
  "gear-a10-last-oracle-staff": "/assets/gear-icons/staff-02.webp",
  "item-a11-star-metal": "/assets/items/silver-ore.webp",
  "item-a11-astral-glass": "/assets/items/arcane-crystal.webp",
  "item-a11-comet-silk": "/assets/items/fine-cloth.webp",
  "gear-a11-starforged-head": "/assets/gear-icons/head-01.webp",
  "gear-a11-starforged-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a11-starforged-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a11-starforged-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a11-starforged-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a11-voidstrider-head": "/assets/gear-icons/head-02.webp",
  "gear-a11-voidstrider-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a11-voidstrider-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a11-voidstrider-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a11-voidstrider-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a11-astral-savant-head": "/assets/gear-icons/head-03.webp",
  "gear-a11-astral-savant-chest": "/assets/gear-icons/chest-04.webp",
  "gear-a11-astral-savant-pants": "/assets/gear-icons/pants-05.webp",
  "gear-a11-astral-savant-boots": "/assets/gear-icons/boots-01.webp",
  "gear-a11-astral-savant-ring": "/assets/gear-icons/ring-02.webp",
  "gear-a11-cometfall": "/assets/gear-icons/mace-02.webp",
  "gear-a11-orrery-staff": "/assets/gear-icons/staff-03.webp",
  "item-a12-worldroot-heartwood": "/assets/items/hardwood.webp",
  "item-a12-first-echo": "/assets/items/arcane-crystal.webp",
  "item-a12-abyssal-hide": "/assets/items/monster-hide.webp",
  "gear-a12-worldroot-bastion-head": "/assets/gear-icons/head-01.webp",
  "gear-a12-worldroot-bastion-chest": "/assets/gear-icons/chest-02.webp",
  "gear-a12-worldroot-bastion-pants": "/assets/gear-icons/pants-03.webp",
  "gear-a12-worldroot-bastion-boots": "/assets/gear-icons/boots-04.webp",
  "gear-a12-worldroot-bastion-ring": "/assets/gear-icons/ring-05.webp",
  "gear-a12-deepstalker-head": "/assets/gear-icons/head-02.webp",
  "gear-a12-deepstalker-chest": "/assets/gear-icons/chest-03.webp",
  "gear-a12-deepstalker-pants": "/assets/gear-icons/pants-04.webp",
  "gear-a12-deepstalker-boots": "/assets/gear-icons/boots-05.webp",
  "gear-a12-deepstalker-ring": "/assets/gear-icons/ring-01.webp",
  "gear-a12-first-tongue-head": "/assets/gear-icons/head-03.webp",
  "gear-a12-first-tongue-chest": "/assets/gear-icons/chest-04.webp",
  "gear-a12-first-tongue-pants": "/assets/gear-icons/pants-05.webp",
  "gear-a12-first-tongue-boots": "/assets/gear-icons/boots-01.webp",
  "gear-a12-first-tongue-ring": "/assets/gear-icons/ring-02.webp",
  "gear-a12-worldsplitter": "/assets/gear-icons/axe-03.webp",
  "gear-a12-voice-below": "/assets/gear-icons/tome-04.webp",
  "consumable-a4-antivenom": "/assets/items/potion-green-normal.webp",
  "consumable-a5-cooling-salve": "/assets/items/potion-blue-normal.webp",
  "consumable-a6-coagulant": "/assets/items/potion-red-normal.webp"
};

export const CRAFTING_MATERIAL_ARTWORK_URLS = [
  "/assets/items/metal-scrap.webp",
  "/assets/items/iron-ore.webp",
  "/assets/items/copper-ore.webp",
  "/assets/items/silver-ore.webp",
  "/assets/items/gold-ore.webp",
  "/assets/items/coal.webp",
  "/assets/items/hardwood.webp",
  "/assets/items/ancient-bark.webp",
  "/assets/items/tanned-leather.webp",
  "/assets/items/fine-cloth.webp",
  "/assets/items/spider-silk.webp",
  "/assets/items/arcane-crystal.webp",
  "/assets/items/frost-shard.webp",
  "/assets/items/ember-core.webp",
  "/assets/items/storm-essence.webp",
  "/assets/items/poison-gland.webp",
  "/assets/items/bone-fragments.webp",
  "/assets/items/monster-hide.webp",
  "/assets/items/moonpetal.webp",
  "/assets/items/glowcap-mushrooms.webp",
  "/assets/items/empty-alchemy-vial.webp",
] as const;

export const CONSUMABLE_POTION_ARTWORK_URLS = [
  "/assets/items/minor-healing-potion.webp",
  "/assets/items/potion-red-normal.webp",
  "/assets/items/potion-red-greater.webp",
  "/assets/items/potion-red-major.webp",
  "/assets/items/potion-red-superior.webp",
  "/assets/items/potion-blue-minor.webp",
  "/assets/items/potion-blue-normal.webp",
  "/assets/items/potion-blue-greater.webp",
  "/assets/items/potion-blue-major.webp",
  "/assets/items/potion-blue-superior.webp",
  "/assets/items/potion-green-minor.webp",
  "/assets/items/potion-green-normal.webp",
  "/assets/items/potion-green-greater.webp",
  "/assets/items/potion-green-major.webp",
  "/assets/items/potion-green-superior.webp",
  "/assets/items/potion-purple-minor.webp",
  "/assets/items/potion-purple-normal.webp",
  "/assets/items/potion-purple-greater.webp",
  "/assets/items/potion-purple-major.webp",
  "/assets/items/potion-purple-superior.webp",
] as const;

export const ITEM_ARTWORK_URLS = [...new Set([
  ...Object.values(ITEM_ICON_URLS).filter((url) => url.startsWith("/assets/items/")),
  ...CONSUMABLE_POTION_ARTWORK_URLS,
  ...CRAFTING_MATERIAL_ARTWORK_URLS,
])];

export function getItemIconUrl(itemId: string): string | undefined {
  return ITEM_ICON_URLS[itemId];
}
