import type { Ability, DamageType } from "../types";

type AbilityDefinition = Omit<Ability, "types"> & { types?: DamageType[] };

const ABILITY_TYPE_OVERRIDES: Record<string, DamageType[]> = {
  PoisonStab: ["physical", "spell"],
  PoisonCloud: ["spell"],
  Contagion: ["spell"],
  Stealth: ["shadow"],
  Evasion: ["shadow"],
  Neurotoxin: ["spell"],
  VenomousStrike: ["physical", "spell"],
  ToxicExplosion: ["spell"],
  Venomborn: ["spell"],
  Focus: ["shadow"],
  Recouperate: ["shadow"],
  SlowingVenom: ["physical", "spell"],
  WeakeningVenom: ["physical", "spell"],
  RabidVenom: ["physical", "spell"],
  CheapShot: ["physical"],
  Pandemic: ["spell"],
  Epidemic: ["spell", "shadow"],
  LightningStrike: ["lightning", "physical"],
  LightSpeed: ["lightning", "physical"],
  CullTheWeak: ["spell", "physical"],
  Combustion: ["fire"],
  ArcaneCombustion: ["fire", "arcane"],
  Thundersnow: ["frost", "lightning"],
  SelfImmolation: ["fire"],
  ArcaneBarrier: ["arcane"],
  FrozenPath: ["frost"],
  Conductor: ["lightning"],
  ManaFracture: ["arcane"],
  RideTheLightning: ["lightning"],
  SearingStrike: ["fire", "physical"],
  FlameCleave: ["fire", "physical"],
  HolyStrike: ["arcane", "physical"],
  Unbreakable: ["physical"],
  BloodBarrier: ["physical"],
  BurningGuard: ["fire", "physical"],
  LayOnHands: ["arcane"],
  FireEater: ["fire"],
  FurnaceBreaker: ["physical", "fire"],
  ExplosiveStrike: ["physical", "fire"],
  BeaconOfLight: ["arcane"],
};

function resolveAbilityTypes(ability: AbilityDefinition): DamageType[] {
  if (ability.types?.length) return [...new Set(ability.types)];
  if (ABILITY_TYPE_OVERRIDES[ability.id]) return [...ABILITY_TYPE_OVERRIDES[ability.id]];
  const componentTypes = ability.damageComponents?.map((component) => component.damageType) ?? [];
  if (componentTypes.length > 0) return [...new Set(componentTypes)];
  if (ability.damageType) return [ability.damageType];
  return [ability.branch === "shadow" ? "shadow" : ability.branch === "arcanist" ? "arcane" : "physical"];
}

const ABILITY_DEFINITIONS: Record<string, AbilityDefinition> = {
  quickSlash: {
    physicalPowerScaling: 0.15,
    spellPowerScaling: 0,
    range: "melee",
    id: "quickSlash", name: "Quick Slash", description: "Deal Physical Damage equal to 15% of your Physical Power. Quick Slash has no cooldown.", energyCost: 1,
    target: "enemy", damageType: "physical", powerScaling: 0.15, icon: "◢", branch: "shadow",
  },
  TwinStrike: {
    range: "melee",
    id: "TwinStrike", name: "Twin Strike", description: "Strike twice. Each hit deals Physical Damage equal to 50% of your Physical Power and triggers on-hit effects separately.", energyCost: 2,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.5, hits: 2, icon: "⫸", branch: "shadow",
  },
  PoisonStab: {
    range: "melee",
    id: "PoisonStab", name: "Poison Stab", description: "Deal Physical Damage equal to 50% of your Physical Power and apply 1 Poison.", energyCost: 3,
    target: "enemy", damageType: "physical", powerScaling: 0.5, icon: "†", branch: "shadow", effect: "poison",
  },
  PoisonCloud: {
    range: "ranged",
    id: "PoisonCloud", name: "Poison Cloud", description: "Apply 2 Poison to all enemies without dealing direct damage.", energyCost: 3,
    cooldownTurns: 2, target: "all_enemies", dealsDamage: false, icon: "☁", branch: "shadow", effect: "poison", statusStacks: 2, vfx: "poison_cloud",
  },
  Contagion: {
    range: "ranged",
    id: "Contagion", name: "Contagion", description: "Copy all Poison stacks from the selected enemy to another random living enemy.", energyCost: 2,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", spreadTargetStatus: "poison", icon: "☣", branch: "shadow", vfx: "contagion",
  },
  Stealth: {
    range: "melee",
    id: "Stealth", name: "Stealth", description: "Enemies cannot target you until the end of your next turn.", energyCost: 2,
    cooldownTurns: 3, target: "self", icon: "◌", branch: "shadow", effect: "stealth", statusDuration: 2, statusExpiresAtTurnStart: false,
  },
  Evasion: {
    range: "melee",
    id: "Evasion", name: "Evasion", description: "Gain 60% Dodge Chance until your next turn. Dodge Chance cannot exceed 50%.", energyCost: 2,
    cooldownTurns: 3, target: "self", icon: "↝", branch: "shadow", effect: "evasion", statusDuration: 1, statusExpiresAtTurnStart: true, vfx: "evasion",
  },
  Neurotoxin: {
    range: "ranged",
    id: "Neurotoxin", name: "Neurotoxin", description: "Consume all Poison on an enemy to Stun it.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", consumeTargetStatus: "poison", icon: "⌁", branch: "shadow", effect: "stun", vfx: "neurotoxin",
  },
  VenomousStrike: {
    range: "melee",
    id: "VenomousStrike", name: "Venomous Strike", description: "Deal Physical Damage equal to 100% of your Physical Power and apply 2 Poison. Deals double damage if the target is already Poisoned.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 1, icon: "†", branch: "shadow", effect: "poison", statusStacks: 2,
    damageModifiers: [{ id: "venomous-strike-poisoned", name: "Venomous Strike", description: "Deals double damage to Poisoned targets.", multiplier: 2, targetHasAnyStatus: ["poison"] }], vfx: "venomous_strike",
  },
  Flurry: {
    range: "melee",
    id: "Flurry", name: "Flurry", description: "Attack five times, dealing Physical Damage equal to 40% of your Physical Power per hit. Each hit chooses a random enemy and can trigger on-hit effects.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.4, hits: 5, randomTargetPerHit: true, attackSequenceDurationMultiplier: 1.4, icon: "≋", branch: "shadow", vfx: "flurry",
  },
  Ambush: {
    range: "melee",
    id: "Ambush", name: "Ambush", description: "Can only be used while Stealthed. Deal Physical Damage equal to 150% of your Physical Power with +50% Critical Strike Chance.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 1.5, requiredSelfStatus: "stealth", critChanceBonusWithStatus: { status: "stealth", bonus: 0.5 }, icon: "◈", branch: "shadow", vfx: "ambush",
  },
  ToxicExplosion: {
    range: "ranged",
    rangedPresentation: "target",
    id: "ToxicExplosion", name: "Toxic Explosion", description: "Detonate all Poison on the target, dealing its remaining duration damage immediately and removing Poison.", energyCost: 5,
    cooldownTurns: 2, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", detonateStatus: "poison", icon: "☣", branch: "shadow", vfx: "toxic_explosion",
  },
  Venomborn: {
    range: "ranged",
    id: "Venomborn", name: "Venomborn", description: "Consume all Poison on the target to heal for the damage it would deal over its full duration.", energyCost: 2,
    cooldownTurns: 6, target: "enemy", dealsDamage: false, requiredTargetStatus: "poison", consumeStatusForHealing: "poison", icon: "♨", branch: "shadow", vfx: "venomborn",
  },
  LightningStrike: {
    range: "melee",
    id: "LightningStrike", name: "Lightning Strike", description: "Deal 50% Physical Power as Physical Damage and 50% Spell Power as Lightning Damage, then apply Electrified for 3 turns.", energyCost: 4,
    cooldownTurns: 4, target: "enemy", damageComponents: [{ damageType: "physical", powerScaling: 0.5 }, { damageType: "lightning", powerScaling: 0.5 }], effect: "electrified", statusDuration: 3, icon: "ϟ", branch: "shadow", vfx: "lightning_strike",
  },
  Focus: {
    range: "melee",
    id: "Focus", name: "Focus", description: "Reset all your other ability cooldowns.", energyCost: 1,
    cooldownTurns: 6, target: "self", effect: "reset_cooldowns", icon: "◎", branch: "shadow", vfx: "focus",
  },
  Recouperate: {
    range: "melee",
    id: "Recouperate", name: "Recuperate", description: "Restore 50% of your maximum Energy.", energyCost: 1,
    cooldownTurns: 4, target: "self", energyRestorePercentOfMax: 0.5, icon: "◉", branch: "shadow", vfx: "recuperate",
  },
  SharpenedBlade: {
    range: "melee",
    id: "SharpenedBlade", name: "Sharpened Blade", description: "Deal 100% Physical Power as damage. This attack ignores Guard and Barrier.", energyCost: 2,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 1, ignoresAbsorption: true, icon: "†", branch: "shadow", vfx: "sharpened_blade",
  },
  SlowingVenom: {
    range: "melee",
    id: "SlowingVenom", name: "Slowing Venom", description: "Consume 50% of the target's Poison, apply Slowed, and deal 75% Physical Power as damage.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 0.75, requiredTargetStatus: "poison", consumeTargetStatus: "poison", consumeTargetStatusRatio: 0.5,
    statusApplications: [{ status: "slowed" }], icon: "⌁", branch: "shadow", vfx: "slowing_venom",
  },
  WeakeningVenom: {
    range: "melee",
    id: "WeakeningVenom", name: "Weakening Venom", description: "Consume 50% of the target's Poison, apply Vulnerable and Weaken, and deal 60% Physical Power as damage.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 0.6, requiredTargetStatus: "poison", consumeTargetStatus: "poison", consumeTargetStatusRatio: 0.5,
    statusApplications: [{ status: "vulnerable" }, { status: "weaken" }], icon: "⌁", branch: "shadow", vfx: "weakening_venom",
  },
  RabidVenom: {
    range: "melee",
    id: "RabidVenom", name: "Rabid Venom", description: "Consume 50% of the target's Poison, apply Reckless, and deal 75% Physical Power as damage.", energyCost: 3,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.75, requiredTargetStatus: "poison", consumeTargetStatus: "poison", consumeTargetStatusRatio: 0.5,
    statusApplications: [{ status: "reckless" }], icon: "⌁", branch: "shadow", vfx: "rabid_venom",
  },
  PinpointSlice: {
    range: "melee",
    id: "PinpointSlice", name: "Pinpoint Slice", description: "Deal 75% Physical Power as damage. Your next damaging ability is guaranteed to critically strike.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.75, grantsNextCritical: true, icon: "⊙", branch: "shadow", vfx: "pinpoint_slice",
  },
  TraumaticPuncture: {
    range: "melee",
    id: "TraumaticPuncture", name: "Traumatic Puncture", description: "Deal 75% Physical Power as damage. A critical strike also applies Weaken and 2 Bleed.", energyCost: 3,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.75,
    statusApplications: [{ status: "weaken", onlyOnCritical: true }, { status: "bleed", stacks: 2, onlyOnCritical: true }], icon: "‡", branch: "shadow",
  },
  SliceAndDice: {
    range: "melee",
    id: "SliceAndDice", name: "Slice and Dice", description: "Attack six times for 15% Physical Power per hit. Critical hits apply Exhausted. Each hit triggers on-hit effects.", energyCost: 5,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.15, hits: 6, attackSequenceDurationMultiplier: 1.4,
    statusApplications: [{ status: "exhausted", onlyOnCritical: true }], icon: "≋", branch: "shadow", vfx: "slice_and_dice",
  },
  CheapShot: {
    range: "melee",
    id: "CheapShot", name: "Cheap Shot", description: "Stun the target and apply 5 Bleed. Can only be used while Stealthed.", energyCost: 4,
    cooldownTurns: 1, target: "enemy", dealsDamage: false, requiredSelfStatus: "stealth", effect: "stun",
    statusApplications: [{ status: "bleed", stacks: 5 }], icon: "‡", branch: "shadow",
  },
  Pandemic: {
    range: "ranged",
    id: "Pandemic", name: "Pandemic", description: "Copy every debuff on the target to all other living enemies.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, spreadAllTargetDebuffs: true, icon: "☣", branch: "shadow", vfx: "pandemic",
  },
  LightSpeed: {
    range: "melee",
    id: "LightSpeed", name: "Light Speed", description: "Deal 50% Physical Power as Physical Damage and 100% Spell Power as Lightning Damage, apply Electrified, then immediately begin a new turn.", energyCost: 6,
    cooldownTurns: 5,
    target: "enemy", damageComponents: [{ damageType: "physical", powerScaling: 0.5 }, { damageType: "lightning", powerScaling: 1 }],
    statusApplications: [{ status: "electrified" }], grantsImmediateTurn: true, icon: "ϟ", branch: "shadow", vfx: "light_speed", immediateTurnVfx: "light_speed_turn",
  },
  ChainAssassination: {
    range: "melee",
    id: "ChainAssassination", name: "Chain Assassination", description: "Deal 125% Physical Power as damage. While Stealthed, gain +25% Critical Strike Chance. A kill refunds the Energy spent and resets the cooldown.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 1.25,
    critChanceBonusWithStatus: { status: "stealth", bonus: 0.25 }, refundEnergyOnKill: true, resetCooldownOnKill: true, killVfx: "chain_assassination", icon: "◈", branch: "shadow",
  },
  CullTheWeak: {
    range: "ranged",
    id: "CullTheWeak", name: "Cull the Weak", description: "Deal 25% Physical Power as Physical Damage and 25% Spell Power as Spell Damage. Both gain 20% damage per unique debuff on the target.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageComponents: [{ damageType: "physical", powerScaling: 0.25 }, { damageType: "spell", powerScaling: 0.25 }],
    damagePerTargetDebuff: 0.2, icon: "◎", branch: "shadow", vfx: "cull_the_weak",
  },
  Epidemic: {
    range: "ranged",
    id: "Epidemic", name: "Epidemic", description: "Apply 10 Poison to all enemies and gain Stealth until the end of your next turn.", energyCost: 3,
    cooldownTurns: 10, target: "all_enemies", dealsDamage: false, effect: "poison", statusStacks: 10,
    selfStatusApplications: [{ status: "stealth", duration: 2, expiresAtTurnStart: false }], icon: "☣", branch: "shadow", vfx: "epidemic",
  },
  VoltageStab: {
    range: "melee",
    id: "VoltageStab", name: "Voltage Stab", description: "Deal Lightning Damage equal to 35% of your Spell Power. If the target is Electrified, restore 2% of your maximum Health and gain +2 Energy regeneration next turn.", energyCost: 0,
    cooldownTurns: 2, target: "enemy", damageType: "lightning", powerScaling: 0.35,
    conditionalSelfEffects: [{ targetHasStatus: "electrified", healPercentMaxHp: 0.02, nextTurnEnergyRegen: 2, vfx: "voltage_siphon" }], icon: "ϟ", branch: "shadow",
  },
  crushingBlow: {
    range: "melee",
    id: "crushingBlow", name: "Crushing Blow", description: "A heavy strike that leaves the enemy vulnerable.", energyCost: 4,
    target: "enemy", damageType: "physical", power: 12, scalingStat: "strength", icon: "✦", branch: "brute", effect: "vulnerable",
  },
  groundSlam: {
    range: "melee",
    id: "groundSlam", name: "Ground Slam", description: "Damage all enemies with a chance to stun.", energyCost: 6,
    target: "all_enemies", damageType: "physical", power: 7, scalingStat: "strength", icon: "✹", branch: "brute", effect: "stun",
  },
  sever: {
    range: "melee",
    id: "sever", name: "Sever", description: "A swift cut that applies Bleed for 3 turns.", energyCost: 3,
    target: "enemy", damageType: "shadow", power: 7, scalingStat: "agility", icon: "◢", branch: "shadow", effect: "bleed",
  },
  venom: {
    range: "melee",
    id: "venom", name: "Venom Edge", description: "Poison an enemy and deal light damage.", energyCost: 4,
    target: "enemy", damageType: "shadow", power: 5, scalingStat: "agility", icon: "⌁", branch: "shadow", effect: "poison",
  },
  arcaneBolt: {
    range: "ranged",
    id: "arcaneBolt", name: "Arcane Bolt", description: "Deal Arcane Damage equal to 75% of your Spell Power.", energyCost: 1,
    cooldownTurns: 1, target: "enemy", damageType: "arcane", powerScaling: 0.75, icon: "✧", branch: "arcanist", vfx: "arcane_bolt",
  },
  Frostbolt: {
    range: "ranged",
    id: "Frostbolt", name: "Frostbolt", description: "Deal Frost Damage equal to 50% of your Spell Power and have a 50% chance to apply Slowed.", energyCost: 3,
    cooldownTurns: 1, target: "enemy", damageType: "frost", powerScaling: 0.5, statusApplications: [{ status: "slowed", chance: 0.5 }], icon: "❄", branch: "arcanist", vfx: "frostbolt",
  },
  ArcaneBlast: {
    range: "ranged",
    id: "ArcaneBlast", name: "Arcane Blast", description: "Deal Arcane Damage equal to 20% of your Spell Power plus an additional 10% of your Spell Power per existing Arcane Wound, then apply 1 Arcane Wound.", energyCost: 1,
    target: "enemy", damageType: "arcane", powerScaling: 0.2, statusApplications: [{ status: "arcaneWound" }], damagePerTargetStatusStack: { status: "arcaneWound", powerScaling: 0.1 }, freeAgainstTargetStatus: "arcaneCharge", icon: "✦", branch: "arcanist", vfx: "arcane_blast",
  },
  Fireball: {
    range: "ranged",
    id: "Fireball", name: "Fireball", description: "Deal Fire Damage equal to 100% of your Spell Power and apply 2 Burn.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "fire", powerScaling: 1, statusApplications: [{ status: "burn", stacks: 2 }], icon: "●", branch: "arcanist", vfx: "fireball",
  },
  LightningBeam: {
    range: "ranged",
    id: "LightningBeam", name: "Lightning Beam", description: "Strike random enemies four times for 20% Spell Power as Lightning Damage per hit. Each hit has a 20% chance to apply Electrified.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", damageType: "lightning", powerScaling: 0.2, hits: 4, randomTargetPerHit: true, statusApplications: [{ status: "electrified", chance: 0.2 }], icon: "ϟ", branch: "arcanist", vfx: "lightning_beam",
  },
  Thunderstorm: {
    range: "ranged",
    rangedPresentation: "target",
    id: "Thunderstorm", name: "Thunderstorm", description: "Strike random enemies six times for 30% Spell Power as Lightning Damage per hit. Hits against Electrified enemies deal 50% more damage.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageType: "lightning", powerScaling: 0.3, hits: 6, randomTargetPerHit: true,
    damageModifiers: [{ id: "thunderstorm-electrified", name: "Conductive Storm", description: "Thunderstorm deals 50% more damage to Electrified enemies.", targetHasAnyStatus: ["electrified"], multiplier: 1.5 }], icon: "ϟ", branch: "arcanist", vfx: "thunderstorm",
  },
  DeepFreeze: {
    range: "ranged",
    rangedPresentation: "target",
    id: "DeepFreeze", name: "Deep Freeze", description: "Deal 75% Spell Power as Frost Damage and apply Slowed. If the target is already Slowed, apply Stunned instead.", energyCost: 4,
    cooldownTurns: 4, target: "enemy", damageType: "frost", powerScaling: 0.75, statusApplications: [{ status: "slowed" }],
    conditionalStatusReplacement: { status: "slowed", whenTargetHas: "slowed", replacement: "stunned" }, icon: "❄", branch: "arcanist", vfx: "deep_freeze",
  },
  ArcaneOverload: {
    range: "ranged",
    rangedPresentation: "target",
    id: "ArcaneOverload", name: "Arcane Overload", description: "Deal 50% Spell Power as Arcane Damage, apply 3 Arcane Wounds, and mark the target with Arcane Charge. Your next Arcane Blast against that target costs 0 Energy.", energyCost: 3,
    cooldownTurns: 3, target: "enemy", damageType: "arcane", powerScaling: 0.5,
    statusApplications: [{ status: "arcaneWound", stacks: 3 }, { status: "arcaneCharge" }], icon: "✹", branch: "arcanist", vfx: "arcane_overload",
  },
  Combustion: {
    range: "ranged",
    rangedPresentation: "target",
    id: "Combustion", name: "Combustion", description: "Consume all Burn on the target and deal its remaining damage immediately. If this kills the target, spread half its Burn stacks to all other enemies.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, requiredTargetStatus: "burn", detonateStatus: "burn",
    spreadDetonatedStatusOnKillRatio: 0.5, spreadOnKillVfx: "combustion_spread", icon: "🔥", branch: "arcanist", vfx: "combustion",
  },
  ArcaneCombustion: {
    range: "ranged",
    rangedPresentation: "target",
    id: "ArcaneCombustion", name: "Arcane Combustion", description: "Consume all Arcane Wounds on the target. Deal 50% Spell Power as Fire Damage per stack consumed and apply an equal number of Burn stacks.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", requiredTargetStatus: "arcaneWound", consumeTargetStatus: "arcaneWound",
    consumeTargetStatusForDamage: { status: "arcaneWound", damageType: "fire", powerScalingPerStack: 0.5, applyStatus: "burn", appliedStacksPerConsumedStack: 1 }, icon: "✹", branch: "arcanist", vfx: "arcane_combustion",
  },
  Thundersnow: {
    range: "ranged",
    rangedPresentation: "target",
    id: "Thundersnow", name: "Thundersnow", description: "Hit all enemies for a combined 60% Spell Power as Frost and Lightning Damage. Apply Slowed to every target and Electrified to one random target.", energyCost: 5,
    cooldownTurns: 3, target: "all_enemies", simultaneousAreaImpact: true, damageComponents: [{ damageType: "frost", powerScaling: 0.3 }, { damageType: "lightning", powerScaling: 0.3 }],
    statusApplications: [{ status: "slowed" }], randomSingleStatusApplication: { status: "electrified" }, icon: "❄", branch: "arcanist", vfx: "thundersnow",
  },
  SelfImmolation: {
    range: "ranged",
    id: "SelfImmolation", name: "Self Immolation", description: "Apply 5 Burn to yourself and the selected enemy.", energyCost: 1,
    cooldownTurns: 5, target: "enemy", dealsDamage: false, effect: "burn", statusStacks: 5,
    selfStatusApplications: [{ status: "burn", stacks: 5 }], combineSelfAndTargetStatusEvent: true, selfStatusVfx: "self_immolation", icon: "🔥", branch: "arcanist", vfx: "self_immolation",
  },
  ArcaneBarrier: {
    range: "ranged",
    id: "ArcaneBarrier", name: "Arcane Barrier", description: "Gain Barrier equal to 50% of your Spell Power for 3 turns.", energyCost: 1,
    cooldownTurns: 5, target: "self", dealsDamage: false, effect: "barrier", statusDuration: 3,
    statusStackPowerScaling: { power: "magical", scaling: 0.5 }, icon: "◇", branch: "arcanist", vfx: "arcane_barrier",
  },
  FrozenPath: {
    range: "ranged",
    id: "FrozenPath", name: "Frozen Path", description: "Gain 30% Dodge Chance for 3 turns. Dodge Chance cannot exceed 50%.", energyCost: 1,
    cooldownTurns: 5, target: "self", dealsDamage: false, effect: "frozenPath", statusDuration: 3, statusMagnitude: 0.3,
    icon: "❄", branch: "arcanist", vfx: "frozen_path",
  },
  Conductor: {
    range: "ranged",
    id: "Conductor", name: "Conductor", description: "Stun all enemies and yourself for 1 turn.", energyCost: 1,
    cooldownTurns: 5, target: "all_enemies", dealsDamage: false, effect: "stunned", statusDuration: 1,
    selfStatusApplications: [{ status: "stunned", duration: 2 }], selfStatusVfx: "conductor", icon: "ϟ", branch: "arcanist", vfx: "conductor",
  },
  Firestorm: {
    range: "ranged",
    rangedPresentation: "target",
    id: "Firestorm", name: "Firestorm", description: "Deal Fire Damage equal to 25% of your Spell Power to all enemies, then apply 2 Burn to all enemies and yourself.", energyCost: 5,
    cooldownTurns: 3, target: "all_enemies", simultaneousAreaImpact: true, damageType: "fire", powerScaling: 0.25, effect: "burn", statusStacks: 2,
    selfStatusApplications: [{ status: "burn", stacks: 2 }], selfStatusVfx: "firestorm", icon: "🔥", branch: "arcanist", vfx: "firestorm",
  },
  ManaFracture: {
    range: "ranged",
    id: "ManaFracture", name: "Mana Fracture", description: "Consume all Arcane Wounds on the target. Restore 1 Energy per 2 stacks consumed.", energyCost: 1,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, requiredTargetStatus: "arcaneWound", consumeTargetStatus: "arcaneWound",
    energyPerConsumedTargetStatusStacks: { stacksPerEnergy: 2 }, icon: "✦", branch: "arcanist", vfx: "mana_fracture",
  },
  RapidFire: {
    range: "ranged",
    id: "RapidFire", name: "Rapid Fire", description: "Attack random enemies three times for 30% Spell Power as Fire Damage per hit, with +20% Critical Strike Chance. While Burning, attack six times instead.", energyCost: 2,
    cooldownTurns: 4, target: "enemy", damageType: "fire", powerScaling: 0.3, hits: 3, hitsWhenSelfHasStatus: { status: "burn", hits: 6 }, randomTargetPerHit: true,
    critChanceBonus: 0.2, attackSequenceDurationMultiplier: 1.4, icon: "✦", branch: "arcanist", vfx: "rapid_fire",
  },
  FocusedBlast: {
    range: "ranged",
    id: "FocusedBlast", name: "Focused Blast", description: "Requires at least 6 Arcane Wounds. Deal Arcane Damage equal to your Barrier and consume 3 Arcane Wounds.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "arcane", requiredTargetStatusStacks: { status: "arcaneWound", minimum: 6 }, consumeTargetStatus: "arcaneWound", consumeTargetStatusStacks: 3,
    damageFromSelfStatusStacks: { status: "barrier", multiplier: 1, damageType: "arcane" }, icon: "✦", branch: "arcanist", vfx: "focused_blast",
  },
  AbsoluteZero: {
    range: "ranged",
    rangedPresentation: "target",
    id: "AbsoluteZero", name: "Absolute Zero", description: "Deal Frost Damage equal to 50% of your Spell Power. If the target is Slowed, apply Frozen; otherwise apply Slowed and Exhausted.", energyCost: 3,
    cooldownTurns: 4, target: "enemy", damageType: "frost", powerScaling: 0.5, statusApplications: [{ status: "slowed" }, { status: "exhausted" }],
    conditionalStatusApplications: { whenTargetHas: "slowed", applications: [{ status: "frozen" }] }, icon: "❄", branch: "arcanist", vfx: "absolute_zero",
  },
  Blizzard: {
    range: "ranged",
    rangedPresentation: "target",
    id: "Blizzard", name: "Blizzard", description: "Deal Frost Damage equal to 50% of your Spell Power to all enemies. Each target has a 50% chance to become Slowed, a 50% chance to become Exhausted, and a 10% chance to become Frozen.", energyCost: 5,
    cooldownTurns: 3, target: "all_enemies", simultaneousAreaImpact: true, damageType: "frost", powerScaling: 0.5,
    statusApplications: [{ status: "slowed", chance: 0.5 }, { status: "exhausted", chance: 0.5 }, { status: "frozen", chance: 0.1 }], icon: "❄", branch: "arcanist", vfx: "blizzard",
  },
  RideTheLightning: {
    range: "ranged",
    id: "RideTheLightning", name: "Ride the Lightning", description: "Consume Electrified from all enemies, immediately begin a new turn, and restore 1 Energy per enemy affected.", energyCost: 1,
    cooldownTurns: 6, target: "enemy", dealsDamage: false, consumeStatusFromAllEnemies: "electrified", energyPerConsumedEnemyStatus: 1,
    grantsImmediateTurn: true, immediateTurnVfx: "ride_the_lightning", selfStatusVfx: "ride_the_lightning", icon: "ϟ", branch: "arcanist", vfx: "ride_the_lightning",
  },
  Charge: {
    range: "ranged",
    rangedPresentation: "target",
    id: "Charge", name: "Charge", description: "Consume Electrified from all enemies. For each enemy affected, reduce all ability cooldowns by 1 and restore 1 Energy, then deal Lightning Damage equal to 100% of your Spell Power to all enemies.", energyCost: 4,
    cooldownTurns: 6, target: "all_enemies", damageType: "lightning", powerScaling: 1, consumeStatusFromAllEnemies: "electrified",
    energyPerConsumedEnemyStatus: 1, cooldownReductionPerConsumedEnemyStatus: 1, consumeStatusFromAllEnemiesVfx: "charge_siphon", icon: "ϟ", branch: "arcanist", vfx: "charge",
  },
  ElementalFury: {
    range: "ranged",
    id: "ElementalFury", name: "Elemental Fury", description: "Deal Arcane Damage equal to 50% of your Spell Power. If the target has no debuffs, apply 2 Burn, Electrified, Slowed, Exhausted, and 2 Arcane Wounds. Otherwise, deal 50% more damage per unique debuff on the target.", energyCost: 3,
    cooldownTurns: 6, target: "enemy", damageType: "arcane", powerScaling: 0.5, damagePerTargetDebuff: 0.5,
    statusApplicationsWhenTargetHasNoDebuffs: [{ status: "burn", stacks: 2 }, { status: "electrified" }, { status: "slowed" }, { status: "exhausted" }, { status: "arcaneWound", stacks: 2 }],
    icon: "✹", branch: "arcanist", vfx: "elemental_fury",
  },
  SearingStrike: {
    range: "melee",
    id: "SearingStrike", name: "Searing Strike", description: "Deal Physical Damage equal to 90% of your Physical Power and apply 1 Burn.", energyCost: 3,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 0.9, statusApplications: [{ status: "burn" }], icon: "✦", branch: "brute", vfx: "searing_strike",
  },
  Bash: {
    range: "melee",
    id: "Bash", name: "Bash", description: "Deal Physical Damage equal to 60% of your Physical Power. Has a 30% chance to grant +1 Energy regeneration next turn.", energyCost: 1,
    cooldownTurns: 1, target: "enemy", damageType: "physical", powerScaling: 0.6, icon: "✦", branch: "brute", vfx: "bash",
  },
  WoundingStrike: {
    range: "melee",
    id: "WoundingStrike", name: "Wounding Strike", description: "Deal Physical Damage equal to 40% of your Physical Power and apply 1 Bleed.", energyCost: 2,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.4, statusApplications: [{ status: "bleed" }], icon: "✦", branch: "brute", vfx: "wounding_strike",
  },
  SwiftBlade: {
    range: "melee",
    id: "SwiftBlade", name: "Swift Blade", description: "Deal Physical Damage equal to 40% of your Physical Power and gain +1 Energy regeneration next turn.", energyCost: 0,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.4, nextTurnEnergyRegenOnHit: 1, icon: "✦", branch: "brute", vfx: "swift_blade",
  },
  FlameCleave: {
    range: "melee",
    id: "FlameCleave", name: "Flame Cleave", description: "Deal Physical Damage equal to 60% of your Physical Power to all enemies and apply 1 Burn.", energyCost: 4,
    cooldownTurns: 3, target: "all_enemies", simultaneousAreaImpact: true, damageType: "physical", powerScaling: 0.6, statusApplications: [{ status: "burn" }], icon: "✦", branch: "brute", vfx: "flame_cleave",
  },
  ShieldBash: {
    range: "melee",
    id: "ShieldBash", name: "Shield Bash", description: "Deal Physical Damage equal to 60% of your Physical Power and gain Guard equal to 10% of your Armor.", energyCost: 2,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.6, selfGuardFromArmorRatio: 0.1, icon: "✦", branch: "brute", vfx: "shield_bash",
  },
  Bloodletting: {
    range: "melee",
    id: "Bloodletting", name: "Bloodletting", description: "Deal Physical Damage equal to 75% of your Physical Power. Apply 1 Bleed for every 3 Bleed already on the target.", energyCost: 3,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.75, statusApplicationPerTargetStatusStacks: { status: "bleed", targetStatus: "bleed", divisor: 3 }, icon: "✦", branch: "brute", vfx: "bloodletting",
  },
  HolyStrike: {
    range: "melee",
    id: "HolyStrike", name: "Holy Strike", description: "Deal Physical Damage equal to 75% of your Physical Power and restore 2% of your maximum Health.", energyCost: 2,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.75, selfHealPercentMaxHp: 0.02, icon: "✦", branch: "brute", vfx: "holy_strike",
  },
  Unbreakable: {
    range: "melee",
    id: "Unbreakable", name: "Unbreakable", description: "Gain Guard equal to 100% of your Armor.", energyCost: 3,
    cooldownTurns: 5, target: "self", dealsDamage: false, selfGuard: { armorScaling: 1, duration: 1 }, icon: "✦", branch: "brute", vfx: "unbreakable",
  },
  BloodBarrier: {
    range: "melee",
    id: "BloodBarrier", name: "Blood Barrier", description: "Consume up to 5 Bleed from the target. Gain Guard equal to 10% of your maximum Health per stack consumed.", energyCost: 2,
    cooldownTurns: 3, target: "enemy", dealsDamage: false, requiredTargetStatus: "bleed", consumeTargetStatus: "bleed", consumeTargetStatusStacks: 5,
    guardPerConsumedTargetStatusStackMaxHpRatio: 0.1, icon: "✦", branch: "brute", vfx: "blood_barrier", vfxDirection: "to_player",
  },
  BurningGuard: {
    range: "melee",
    id: "BurningGuard", name: "Burning Guard", description: "Gain Guard equal to 50% of your Physical Power for 1 turn. If this Guard is destroyed, apply 3 Burn to the attacker.", energyCost: 2,
    cooldownTurns: 4, target: "self", dealsDamage: false, selfGuard: { physicalPowerScaling: 0.5, duration: 1 }, icon: "✦", branch: "brute", vfx: "burning_guard",
  },
  LayOnHands: {
    range: "melee",
    id: "LayOnHands", name: "Lay on Hands", description: "Restore 10% of your maximum Health. Gain Barrier equal to the Health restored.", energyCost: 5,
    cooldownTurns: 5, target: "self", dealsDamage: false, selfHealPercentMaxHp: 0.1, barrierFromSelfHealingRatio: 1, icon: "✦", branch: "brute", vfx: "lay_on_hands",
  },
  ShieldCharge: {
    range: "melee",
    id: "ShieldCharge", name: "Shield Charge", description: "Deal Physical Damage equal to 25% of your Physical Power plus 50% of your Armor. Stun the target if you have Guard.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", damageType: "physical", damageComponents: [{ damageType: "physical", powerScaling: 0.25, armorScaling: 0.5 }],
    statusApplicationsWhenSelfHas: { selfStatus: "guard", applications: [{ status: "stunned" }] }, icon: "✦", branch: "brute", vfx: "shield_charge",
  },
  Bloodbath: {
    range: "melee",
    id: "Bloodbath", name: "Bloodbath", description: "Strike 5 times, choosing a random enemy for each hit. Each hit deals Physical Damage equal to 50% of your Physical Power and applies 1 Bleed.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.5, hits: 5, randomTargetPerHit: true, statusApplications: [{ status: "bleed" }], icon: "✦", branch: "brute", vfx: "bloodbath",
  },
  FurnaceBreaker: {
    range: "melee",
    id: "FurnaceBreaker", name: "Furnace Breaker", description: "Deal Physical Damage equal to 100% of your Physical Power. Immediately trigger the target's Burn damage once without removing Burn.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 1, triggerTargetStatusDamage: "burn", icon: "✦", branch: "brute", vfx: "furnace_breaker",
  },
  DivineSmite: {
    range: "ranged", rangedPresentation: "target",
    id: "DivineSmite", name: "Divine Smite", description: "Deal Magic Damage equal to 100% of your Spell Power and apply Smite for 3 turns.", energyCost: 5,
    cooldownTurns: 5, target: "enemy", damageType: "arcane", powerScaling: 1, statusApplications: [{ status: "smite", duration: 3 }], icon: "✦", branch: "brute", vfx: "divine_smite",
  },
  BloodFrenzy: {
    range: "melee",
    id: "BloodFrenzy", name: "Blood Frenzy", description: "Attack four times for 35% Physical Power per hit. Each hit applies 1 Bleed. While Fierce, attack six times instead.", energyCost: 5,
    cooldownTurns: 3, target: "enemy", damageType: "physical", powerScaling: 0.35, hits: 4, hitsWhenSelfHasStatus: { status: "fierce", hits: 6 },
    statusApplications: [{ status: "bleed" }], icon: "✦", branch: "brute", vfx: "blood_frenzy",
  },
  CrushingImpact: {
    range: "melee",
    id: "CrushingImpact", name: "Crushing Impact", description: "Deal Physical Damage equal to your Guard and remove every buff from the target.", energyCost: 4,
    cooldownTurns: 3, target: "enemy", damageFromSelfStatusStacks: { status: "guard", multiplier: 1, damageType: "physical" }, removeAllTargetBuffs: true,
    icon: "✦", branch: "brute", vfx: "crushing_impact",
  },
  ExplosiveStrike: {
    range: "melee",
    id: "ExplosiveStrike", name: "Explosive Strike", description: "Deal Physical Damage equal to 50% of your Physical Power, increased by 5% per Burn on the target. Consume all of that Burn to deal its remaining damage to every other enemy.", energyCost: 4,
    cooldownTurns: 2, target: "enemy", damageType: "physical", powerScaling: 0.5, damagePerTargetStatusStack: { status: "burn", multiplier: 0.05 },
    consumeTargetStatusForOtherEnemiesDamage: { status: "burn", damageType: "fire", vfx: "explosive_strike_blast" }, icon: "✦", branch: "brute", vfx: "explosive_strike",
  },
  ConsecratedGround: {
    range: "ranged", rangedPresentation: "target",
    id: "ConsecratedGround", name: "Consecrated Ground", description: "Deal Magic Damage equal to 80% of your Spell Power to all enemies. Each enemy has a 20% chance to gain Smite. Gain Regenerate.", energyCost: 6,
    cooldownTurns: 4, target: "all_enemies", simultaneousAreaImpact: true, damageType: "arcane", powerScaling: 0.8,
    statusApplications: [{ status: "smite", chance: 0.2 }], selfStatusApplications: [{ status: "regenerate" }], selfStatusVfx: "consecrated_ground",
    icon: "✦", branch: "brute", vfx: "consecrated_ground",
  },
  BruteGuard: {
    range: "melee",
    id: "BruteGuard", name: "Guard", description: "Gain Guard equal to 5% of your Armor.", energyCost: 1,
    target: "self", dealsDamage: false, selfGuard: { armorScaling: 0.05, duration: 1 }, icon: "✦", branch: "brute", vfx: "brute_guard",
  },
  Vampirism: {
    range: "melee",
    id: "Vampirism", name: "Vampirism", description: "Deal Physical Damage equal to 10% of your Physical Power and restore 2 Health per Bleed on the target.", energyCost: 2,
    target: "enemy", damageType: "physical", powerScaling: 0.1, selfHealPerTargetStatusStack: { status: "bleed", multiplier: 2, vfx: "vampirism_drain" }, icon: "✦", branch: "brute", vfx: "vampirism",
  },
  FireEater: {
    range: "melee",
    id: "FireEater", name: "Fire Eater", description: "Consume all Burn on yourself. Restore Health equal to its remaining damage and apply the consumed Burn to the selected enemy.", energyCost: 4,
    cooldownTurns: 4, target: "enemy", dealsDamage: false, requiredSelfStatus: "burn", transferSelfStatusToTargetForHealing: { status: "burn", selfVfx: "fire_eater", transferVfx: "fire_eater_transfer" }, icon: "✦", branch: "brute", vfx: "fire_eater",
  },
  BeaconOfLight: {
    range: "ranged", rangedPresentation: "target",
    id: "BeaconOfLight", name: "Beacon of Light", description: "Apply Smite to all enemies. Gain Regenerate for 3 turns.", energyCost: 6,
    cooldownTurns: 6, target: "all_enemies", dealsDamage: false, effect: "smite", areaVfxPerTarget: true, selfStatusApplications: [{ status: "regenerate", duration: 3 }], selfStatusVfx: "beacon_of_light", icon: "✦", branch: "brute", vfx: "beacon_of_light",
  },
  siphon: {
    range: "ranged",
    rangedPresentation: "target",
    id: "siphon", name: "Essence Siphon", description: "Deal damage and recover 2 Energy.", energyCost: 4,
    target: "enemy", damageType: "arcane", power: 7, scalingStat: "intelligence", icon: "◎", branch: "arcanist", effect: "energy", vfx: "essence_siphon", vfxDirection: "to_player",
  },
};

export const ABILITIES: Record<string, Ability> = Object.fromEntries(
  Object.entries(ABILITY_DEFINITIONS).map(([id, ability]) => [id, { ...ability, types: resolveAbilityTypes(ability) }]),
);
