import type { EnemyTemplate } from "../types";

export const ENEMIES: Record<string, EnemyTemplate> = {
  dummy: { id: "dummy", name: "DUMMY", title: "Training Construct", imageUrl: "/assets/enemies/full/dummy.webp", portraitUrl: "/assets/enemies/portraits/dummy.webp", maxHp: 100, physicalPower: 1, spellPower: 0, armor: 0, magicResistance: 0, hitChance: 0.95, dodgeChance: 0, critChance: 0, energyRegen: 1, maxEnergy: 10, abilities: [{ id: "trainingStrike", name: "Training Strike", description: "Deals 1 base Physical damage.", energyCost: 1, cooldownTurns: 0, range: "melee", damageType: "physical", baseDamage: 1, vfx: "enemy_training_strike" }], behaviorNotes: "Uses Training Strike whenever it has enough Energy.", behavior: "single", maxActionsPerTurn: 1, accent: "#a8a69d" },
  "enemy-mrxiut2a-k4kgv": { id: "enemy-mrxiut2a-k4kgv", name: "Rabid Rat", title: "Creature", imageUrl: "/assets/enemies/full/rabid-rat.webp", portraitUrl: "/assets/enemies/portraits/rabid-rat.webp", maxHp: 11, physicalPower: 1, spellPower: 0, armor: 0, magicResistance: 0, hitChance: 0.95, dodgeChance: 0.05, critChance: 0.1, energyRegen: 1, maxEnergy: 3, abilities: [
    { id: "enemy-ability-mrxjymmz-fomw6", name: "Bite", description: "Deals 100% Physical Power as Physical damage.", energyCost: 2, cooldownTurns: 1, range: "melee", damageType: "physical", physicalPowerScaling: 1, vfx: "enemy_bite" },
    { id: "enemy-ability-mrxk052s-zrgdh", name: "Scurry", description: "Recovers 1 extra Energy next turn.", energyCost: 0, cooldownTurns: 1, range: "melee", nextTurnEnergyRegen: 1, vfx: "enemy_scurry" },
    { id: "enemy-ability-mrxk0xn3-cg5w8", name: "Rabid Bite", description: "Deals 100% Physical Power as Physical damage and applies 1 Poison.", energyCost: 3, cooldownTurns: 2, range: "melee", damageType: "physical", physicalPowerScaling: 1, statusApplications: [{ status: "poison", stacks: 1 }], vfx: "enemy_rabid_bite" },
  ], behaviorNotes: "Starts with Bite, then Scurries until Rabid Bite is available. Afterwards it Scurries until Bite is available and repeats.", behavior: "rabid_rat", maxActionsPerTurn: 1, accent: "#79a86d" },
  "enemy-mrxj4o6o-o45ia": { id: "enemy-mrxj4o6o-o45ia", name: "Windsong Wolf", title: "Creature", imageUrl: "/assets/enemies/full/windsong-wolf.webp", portraitUrl: "/assets/enemies/portraits/windsong-wolf.webp", maxHp: 20, physicalPower: 2, spellPower: 0, armor: 0, magicResistance: 0, hitChance: 0.95, dodgeChance: 0.1, critChance: 0.1, energyRegen: 1, maxEnergy: 6, abilities: [
    { id: "enemy-ability-mrxjymmz-6ubjd", name: "Howl", description: "Applies Vulnerable.", energyCost: 0, cooldownTurns: 5, range: "ranged", rangedPresentation: "target", statusApplications: [{ status: "vulnerable" }], vfx: "enemy_howl" },
    { id: "enemy-ability-mrxk2rt1-qaobv", name: "Bite and Claw", description: "Strikes twice for 50% Physical Power as Physical damage per hit. Each hit has a 20% chance to apply Bleed.", energyCost: 2, cooldownTurns: 1, range: "melee", damageType: "physical", physicalPowerScaling: 0.5, hits: 2, statusApplications: [{ status: "bleed", chance: 0.2 }], vfx: "enemy_bite_claw" },
  ], behaviorNotes: "Always uses Howl when ready, then uses Bite and Claw when it has enough Energy.", behavior: "priority", maxActionsPerTurn: 1, accent: "#79a86d" },
  "enemy-mrxk609z-n04fq": { id: "enemy-mrxk609z-n04fq", name: "Forest Wisp", title: "Creature", imageUrl: "/assets/enemies/full/forest-wisp.webp", portraitUrl: "/assets/enemies/portraits/forest-wisp.webp", maxHp: 9, physicalPower: 0, spellPower: 2, armor: 0, magicResistance: 1, hitChance: 0.95, dodgeChance: 0.05, critChance: 0.05, energyRegen: 2, maxEnergy: 4, abilities: [{ id: "enemy-ability-mrxk7ose-fc13q", name: "Wisp Blast", description: "Deals Arcane damage equal to a random 50–100% of Spell Power and has a 10% chance to apply Weaken. When its final blast spends all Energy, the Forest Wisp becomes Stunned for 1 turn.", energyCost: 1, cooldownTurns: 0, range: "ranged", rangedPresentation: "projectile", damageType: "arcane", powerScalingRange: { power: "spell", min: 0.5, max: 1 }, statusApplications: [{ status: "weaken", chance: 0.1 }], selfStatusApplicationsWhenEnergyDepleted: [{ status: "stunned", duration: 2 }], vfx: "enemy_wisp_blast" }], behaviorNotes: "Uses Wisp Blast repeatedly until its Energy is empty, then becomes Stunned for its next turn.", behavior: "wisp_barrage", maxActionsPerTurn: 10, accent: "#79a86d" },
  "enemy-mrxkar5z-g9o5d": { id: "enemy-mrxkar5z-g9o5d", name: "Brown Bear", title: "Creature", imageUrl: "/assets/enemies/full/brown-bear.webp", portraitUrl: "/assets/enemies/portraits/brown-bear.webp", maxHp: 30, physicalPower: 3, spellPower: 0, armor: 5, magicResistance: 0, hitChance: 0.85, dodgeChance: 0.05, critChance: 0.05, energyRegen: 0, maxEnergy: 6, abilities: [
    { id: "enemy-ability-mrxkdwnl-vont1", name: "Maul", description: "Deals 100% Physical Power as Physical damage and applies 1 Bleed.", energyCost: 3, cooldownTurns: 1, range: "melee", damageType: "physical", physicalPowerScaling: 1, statusApplications: [{ status: "bleed", stacks: 1 }], vfx: "enemy_maul" },
    { id: "enemy-ability-mrxkeegm-8fny8", name: "Hibernate", description: "Gains Sleep and recovers 6 extra Energy next turn.", energyCost: 0, cooldownTurns: 1, range: "melee", selfStatusApplications: [{ status: "sleep", duration: 2 }], nextTurnEnergyRegen: 6, vfx: "enemy_hibernate" },
    { id: "enemy-ability-mrxkfj6b-snlgn", name: "Roar", description: "Applies Weaken and Vulnerable.", energyCost: 3, cooldownTurns: 6, range: "ranged", rangedPresentation: "target", statusApplications: [{ status: "weaken" }, { status: "vulnerable" }], vfx: "enemy_roar" },
  ], behaviorNotes: "Opens with Roar and Maul. Uses Hibernate when it has no Energy, and otherwise uses Maul while Roar is cooling down.", behavior: "brown_bear", maxActionsPerTurn: 1, accent: "#79a86d" },
  "enemy-mrxkjqs3-g7g5i": { id: "enemy-mrxkjqs3-g7g5i", name: "The Forest Spirit", title: "Creature", imageUrl: "/assets/enemies/full/forest-spirit.webp", portraitUrl: "/assets/enemies/portraits/forest-spirit.webp", maxHp: 40, physicalPower: 0, spellPower: 8, armor: 1, magicResistance: 1, hitChance: 0.95, dodgeChance: 0.1, critChance: 0.1, energyRegen: 2, maxEnergy: 10, abilities: [
    { id: "enemy-ability-mrxkkzcu-tqzsj", name: "Fade Out", description: "Gains Stealth until the end of its next turn and recovers 2 extra Energy next turn.", energyCost: 3, cooldownTurns: 5, range: "ranged", rangedPresentation: "target", selfStatusApplications: [{ status: "stealth" }], nextTurnEnergyRegen: 2, vfx: "enemy_fade_out" },
    { id: "enemy-ability-mrxkmol2-9006k", name: "Burning Glare", description: "Deals 75% Spell Power as Fire damage and applies 1 Burn.", energyCost: 2, cooldownTurns: 2, range: "ranged", rangedPresentation: "projectile", damageType: "fire", spellPowerScaling: 0.75, statusApplications: [{ status: "burn", stacks: 1 }], vfx: "enemy_burning_glare" },
    { id: "enemy-ability-mrxknrod-80ona", name: "Nature's Beam", description: "Deals 100% Spell Power as Arcane damage and applies Weaken.", energyCost: 3, cooldownTurns: 1, range: "ranged", rangedPresentation: "projectile", damageType: "arcane", spellPowerScaling: 1, statusApplications: [{ status: "weaken" }], vfx: "enemy_natures_beam" },
    { id: "enemy-ability-mrxkq0sr-q1e8h", name: "Shimmer", description: "Restores full Energy next turn.", energyCost: 0, cooldownTurns: 5, range: "ranged", rangedPresentation: "target", restoreFullEnergyNextTurn: true, vfx: "enemy_shimmer" },
  ], behaviorNotes: "Fights with two Forest Wisps. Whenever one dies, the Forest Spirit restores 25% of its maximum Health.", behavior: "forest_spirit", maxActionsPerTurn: 1, healOnAllyDeath: { allyId: "enemy-mrxk609z-n04fq", maxHpRatio: 0.25, vfx: "enemy_spirit_heal" }, accent: "#79a86d" },
};
