import type { QuestDefinition, QuestlineDefinition } from "../types";

export const QUESTS: QuestDefinition[] = [
  {
    id: "quest-rats-at-the-storehouses",
    title: "Rats at the Storehouses",
    description: "The grain keepers need someone to thin the swarms nesting along the forest road.",
    objective: { type: "kill_enemy", enemyId: "enemy-mrxiut2a-k4kgv", quantity: 3 },
    reward: { experience: 35, items: [{ itemId: "consumable-ms0e551z-v6qcf", quantity: 1 }] },
  },
  {
    id: "quest-tails-for-the-tally",
    title: "Tails for the Tally",
    description: "Bring back proof that the storehouse paths are being cleared of vermin.",
    objective: { type: "collect_item", itemId: "item-ms0jej41-7sii2", quantity: 2 },
    reward: { experience: 50, items: [] },
  },
  {
    id: "quest-quiet-the-windsong",
    title: "Quiet the Windsong",
    description: "See the trouble in Windsong Forest through to its end and return with news of the road.",
    objective: { type: "complete_adventure", adventureId: "windsong-forest", quantity: 1 },
    reward: { experience: 100, items: [{ itemId: "item-ms0jf0sp-z8hcl", quantity: 1 }] },
  },

  // Roadwarden's Ledger — one escalating enemy bounty for every story adventure.
  {
    id: "quest-ledger-windsong-wolves",
    title: "Fangs Along the Road",
    description: "Windsong Wolves are stalking the road crews. Break the packs before they close the forest path.",
    objective: { type: "kill_enemy", enemyId: "enemy-mrxj4o6o-o45ia", quantity: 3 },
    reward: { experience: 60, items: [{ itemId: "consumable-ms0e551z-v6qcf", quantity: 1 }] },
  },
  {
    id: "quest-ledger-highlands-quickstabbers",
    title: "Knives in the Heather",
    description: "Goblin Quickstabbers are cutting down messengers in the Highlands. Thin their ambush parties.",
    objective: { type: "kill_enemy", enemyId: "enemy-ms1fgqar-mafv9", quantity: 4 },
    reward: { experience: 160, items: [] },
  },
  {
    id: "quest-ledger-highfall-trolls",
    title: "Tolls Paid in Stone",
    description: "Hill Trolls have claimed the Highfall switchbacks. Clear enough of them to reopen the ascent.",
    objective: { type: "kill_enemy", enemyId: "enemy-ms2vrqbb-8r5ux", quantity: 3 },
    reward: { experience: 300, items: [] },
  },
  {
    id: "quest-ledger-mirefen-spitters",
    title: "Venom on the Causeway",
    description: "Mirefen Spitters have nested beside the last usable causeways. Destroy the creatures guarding them.",
    objective: { type: "kill_enemy", enemyId: "enemy-a4-mirefen-spitter", quantity: 4 },
    reward: { experience: 600, items: [{ itemId: "consumable-a4-antivenom", quantity: 1 }] },
  },
  {
    id: "quest-ledger-foundry-acolytes",
    title: "Hands on the Bellows",
    description: "Furnace Acolytes keep the Ashen Foundry awake. Silence the attendants feeding its fires.",
    objective: { type: "kill_enemy", enemyId: "enemy-a5-furnace-acolyte", quantity: 4 },
    reward: { experience: 850, items: [{ itemId: "consumable-a5-cooling-salve", quantity: 1 }] },
  },
  {
    id: "quest-ledger-reliquary-acolytes",
    title: "The Drowned Procession",
    description: "Drowned Acolytes patrol the Reliquary in solemn ranks. Break their procession before it reaches the vault.",
    objective: { type: "kill_enemy", enemyId: "enemy-a6-drowned-acolyte", quantity: 5 },
    reward: { experience: 1150, items: [{ itemId: "consumable-a6-coagulant", quantity: 1 }] },
  },
  {
    id: "quest-ledger-nightglass-stalkers",
    title: "Shapes Behind the Glass",
    description: "Mirror Stalkers are slipping through Nightglass reflections. Hunt them before they reach Arkenfall's roads.",
    objective: { type: "kill_enemy", enemyId: "enemy-a7-mirror-stalker", quantity: 5 },
    reward: { experience: 1500, items: [{ itemId: "item-a7-bloodstone", quantity: 1 }] },
  },
  {
    id: "quest-ledger-expanse-raiders",
    title: "Tracks Across White Silence",
    description: "Icebound Raiders follow every warm trail across the Expanse. End their hunting parties.",
    objective: { type: "kill_enemy", enemyId: "enemy-a8-icebound-raider", quantity: 5 },
    reward: { experience: 2000, items: [{ itemId: "item-a8-white-pelt", quantity: 1 }] },
  },
  {
    id: "quest-ledger-storm-channelers",
    title: "Silence the Conduits",
    description: "Storm Channelers are binding the Aerie's lightning into weapons. Cut their rituals short.",
    objective: { type: "kill_enemy", enemyId: "enemy-a9-storm-channeler", quantity: 5 },
    reward: { experience: 2700, items: [{ itemId: "item-a9-cloudfeather", quantity: 1 }] },
  },
  {
    id: "quest-ledger-hollow-executioners",
    title: "Stay the Royal Axe",
    description: "Veilbound Executioners still obey a kingdom that no longer lives. Put an end to their final sentence.",
    objective: { type: "kill_enemy", enemyId: "enemy-a10-veilbound-executioner", quantity: 6 },
    reward: { experience: 3500, items: [{ itemId: "item-a10-soul-ash", quantity: 1 }] },
  },
  {
    id: "quest-ledger-astral-devourers",
    title: "Hunger Between the Stars",
    description: "Astral Devourers are widening the Scar with every feeding. Destroy them before the breach grows.",
    objective: { type: "kill_enemy", enemyId: "enemy-a11-astral-devourer", quantity: 6 },
    reward: { experience: 4300, items: [{ itemId: "item-a11-comet-silk", quantity: 1 }] },
  },
  {
    id: "quest-ledger-deep-oracles",
    title: "Prophets of the First Dark",
    description: "Deep Oracles are calling something ancient toward the World Below. Silence their chorus.",
    objective: { type: "kill_enemy", enemyId: "enemy-a12-deep-oracle", quantity: 6 },
    reward: { experience: 0, items: [{ itemId: "item-a12-worldroot-heartwood", quantity: 2 }] },
  },

  // Guild Requisitions — biome materials gathered during the matching adventure.
  {
    id: "quest-requisition-wisp-essence",
    title: "Light for the Watch",
    description: "The town watch needs bottled Wisp Essence to relight the forest signal lamps.",
    objective: { type: "collect_item", itemId: "item-ms0jf0sp-z8hcl", quantity: 2 },
    reward: { experience: 75, items: [] },
  },
  {
    id: "quest-requisition-linen-scraps",
    title: "Cloth from the Highlands",
    description: "Arkenfall's healers need clean Linen Scraps recovered from the goblin camps.",
    objective: { type: "collect_item", itemId: "item-ms1if1q6-746wi", quantity: 3 },
    reward: { experience: 190, items: [{ itemId: "item-ms1igebd-dlhst", quantity: 1 }] },
  },
  {
    id: "quest-requisition-frostroot",
    title: "Roots Above the Clouds",
    description: "Highfall Frostroot survives where few gatherers can climb. Bring back enough for the apothecaries.",
    objective: { type: "collect_item", itemId: "item-highfall-frostroot", quantity: 3 },
    reward: { experience: 340, items: [{ itemId: "consumable-highfall-restorative", quantity: 1 }] },
  },
  {
    id: "quest-requisition-venom-sacs",
    title: "Measured Venom",
    description: "The alchemist can turn Mirefen venom into medicine, but only if the sacs arrive intact.",
    objective: { type: "collect_item", itemId: "item-a4-venom-sac", quantity: 3 },
    reward: { experience: 650, items: [{ itemId: "consumable-a4-antivenom", quantity: 1 }] },
  },
  {
    id: "quest-requisition-ember-fragments",
    title: "A Core Still Burning",
    description: "Foundry scholars are paying for Ember Core Fragments that still hold a steady heat.",
    objective: { type: "collect_item", itemId: "item-a5-ember-fragment", quantity: 3 },
    reward: { experience: 900, items: [{ itemId: "consumable-a5-cooling-salve", quantity: 1 }] },
  },
  {
    id: "quest-requisition-relic-shards",
    title: "Fragments of the Drowned",
    description: "The temple archivists need Drowned Relic Shards before the old inscriptions fade.",
    objective: { type: "collect_item", itemId: "item-a6-relic-shard", quantity: 3 },
    reward: { experience: 1250, items: [{ itemId: "consumable-a6-coagulant", quantity: 1 }] },
  },
  {
    id: "quest-requisition-nightglass",
    title: "Shards that Remember",
    description: "Nightglass Shards preserve broken reflections. The jewelers need samples that survived the Citadel.",
    objective: { type: "collect_item", itemId: "item-a7-nightglass", quantity: 4 },
    reward: { experience: 1650, items: [{ itemId: "item-a7-umbral-silk", quantity: 1 }] },
  },
  {
    id: "quest-requisition-frosthearts",
    title: "Cold at the Core",
    description: "Frostheart Crystals can preserve medicine for months. Recover them from the Expanse.",
    objective: { type: "collect_item", itemId: "item-a8-frostheart", quantity: 4 },
    reward: { experience: 2200, items: [{ itemId: "item-a8-white-pelt", quantity: 2 }] },
  },
  {
    id: "quest-requisition-storm-essence",
    title: "A Storm in a Vessel",
    description: "Condensed Storm Essence is needed to protect Arkenfall's tallest towers from the Aerie.",
    objective: { type: "collect_item", itemId: "item-a9-storm-core", quantity: 4 },
    reward: { experience: 2950, items: [{ itemId: "item-a9-cloudfeather", quantity: 2 }] },
  },
  {
    id: "quest-requisition-crown-shards",
    title: "Pieces of an Empty Crown",
    description: "Crown Shards may reveal why the dead kingdom still repeats its last night.",
    objective: { type: "collect_item", itemId: "item-a10-crown-shard", quantity: 4 },
    reward: { experience: 3800, items: [{ itemId: "item-a10-soul-ash", quantity: 2 }] },
  },
  {
    id: "quest-requisition-astral-glass",
    title: "Windows into the Scar",
    description: "Astral Glass bends starlight around impossible angles. Recover intact pieces for study.",
    objective: { type: "collect_item", itemId: "item-a11-astral-glass", quantity: 4 },
    reward: { experience: 4700, items: [{ itemId: "item-a11-comet-silk", quantity: 2 }] },
  },
  {
    id: "quest-requisition-first-echoes",
    title: "Echoes Before Memory",
    description: "The oldest vaults resonate with First Echoes. Bring proof that the sound can be carried home.",
    objective: { type: "collect_item", itemId: "item-a12-first-echo", quantity: 5 },
    reward: { experience: 0, items: [{ itemId: "item-a12-abyssal-hide", quantity: 2 }] },
  },

  // Chronicle of Arkenfall — one expedition report for completing each adventure.
  {
    id: "quest-chronicle-windsong",
    title: "The First Road Opens",
    description: "Complete Windsong Forest and return with an account of what disturbed its heart.",
    objective: { type: "complete_adventure", adventureId: "windsong-forest", quantity: 1 },
    reward: { experience: 120, items: [{ itemId: "item-ms0jd8ky-lu2zb", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-highlands",
    title: "Banners over the Highlands",
    description: "Complete Arkenfall Highlands and record what became of Striz and his goblin host.",
    objective: { type: "complete_adventure", adventureId: "adventure-ms1iq9ye-9ra1z", quantity: 1 },
    reward: { experience: 350, items: [{ itemId: "item-ms1igebd-dlhst", quantity: 1 }] },
  },
  {
    id: "quest-chronicle-highfall",
    title: "The King of Highfall",
    description: "Complete Highfall Mountains and bring the truth of its self-crowned king back to Arkenfall.",
    objective: { type: "complete_adventure", adventureId: "highfall-mountains", quantity: 1 },
    reward: { experience: 650, items: [{ itemId: "consumable-stonebloom-draught", quantity: 1 }] },
  },
  {
    id: "quest-chronicle-mirefen",
    title: "Beyond the Black Water",
    description: "Complete Mirefen Marsh and mark a safe route through the Broodmother's drowned domain.",
    objective: { type: "complete_adventure", adventureId: "mirefen-marsh", quantity: 1 },
    reward: { experience: 1150, items: [{ itemId: "item-a4-bog-iron", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-foundry",
    title: "When the Furnace Falls Silent",
    description: "Complete Ashen Foundry and report whether its endless fire has finally gone dark.",
    objective: { type: "complete_adventure", adventureId: "ashen-foundry", quantity: 1 },
    reward: { experience: 1650, items: [{ itemId: "item-a5-cindersteel", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-reliquary",
    title: "The Seer's Last Tide",
    description: "Complete Sunken Reliquary and recover the final history of its drowned priesthood.",
    objective: { type: "complete_adventure", adventureId: "sunken-reliquary", quantity: 1 },
    reward: { experience: 2300, items: [{ itemId: "item-a6-abyssal-pearl", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-nightglass",
    title: "The Last Reflection",
    description: "Complete Nightglass Citadel and return with a true account of the fortress behind the mirrors.",
    objective: { type: "complete_adventure", adventureId: "nightglass-citadel", quantity: 1 },
    reward: { experience: 3200, items: [{ itemId: "item-a7-bloodstone", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-expanse",
    title: "Across the White Waste",
    description: "Complete Frostbound Expanse and chart the path beyond the White Maw's hunting ground.",
    objective: { type: "complete_adventure", adventureId: "frostbound-expanse", quantity: 1 },
    reward: { experience: 4200, items: [{ itemId: "item-a8-rimebone", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-stormspire",
    title: "Above the Endless Storm",
    description: "Complete Stormspire Aerie and record what waits at the summit beyond the thunderbirds.",
    objective: { type: "complete_adventure", adventureId: "stormspire-aerie", quantity: 1 },
    reward: { experience: 5400, items: [{ itemId: "item-a9-skyiron", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-hollow-crown",
    title: "A Kingdom's Final Night",
    description: "Complete The Hollow Crown and return with the fate of Aldren's dead court.",
    objective: { type: "complete_adventure", adventureId: "hollow-crown", quantity: 1 },
    reward: { experience: 6800, items: [{ itemId: "item-a10-hollowsteel", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-astral-scar",
    title: "Where the Sky Broke",
    description: "Complete The Astral Scar and preserve the truth of the Fallen Star for Arkenfall.",
    objective: { type: "complete_adventure", adventureId: "astral-scar", quantity: 1 },
    reward: { experience: 8000, items: [{ itemId: "item-a11-star-metal", quantity: 2 }] },
  },
  {
    id: "quest-chronicle-world-below",
    title: "The First Hunger Ends",
    description: "Complete The World Below and write the final page of Arkenfall's known road.",
    objective: { type: "complete_adventure", adventureId: "world-below", quantity: 1 },
    reward: { experience: 0, items: [{ itemId: "gear-a12-worldsplitter", quantity: 1 }] },
  },
];

export const QUESTLINES: QuestlineDefinition[] = [
  {
    id: "questline-storehouse-troubles",
    title: "Storehouse Troubles",
    description: "A chain of notices concerning the creatures threatening Arkenfall's food stores.",
    questIds: ["quest-rats-at-the-storehouses", "quest-tails-for-the-tally", "quest-quiet-the-windsong"],
  },
  {
    id: "questline-roadwardens-ledger",
    title: "The Roadwarden's Ledger",
    description: "Escalating bounties against the creatures and warbands blocking every road beyond Arkenfall.",
    questIds: [
      "quest-ledger-windsong-wolves",
      "quest-ledger-highlands-quickstabbers",
      "quest-ledger-highfall-trolls",
      "quest-ledger-mirefen-spitters",
      "quest-ledger-foundry-acolytes",
      "quest-ledger-reliquary-acolytes",
      "quest-ledger-nightglass-stalkers",
      "quest-ledger-expanse-raiders",
      "quest-ledger-storm-channelers",
      "quest-ledger-hollow-executioners",
      "quest-ledger-astral-devourers",
      "quest-ledger-deep-oracles",
    ],
  },
  {
    id: "questline-guild-requisitions",
    title: "Guild Requisitions",
    description: "A standing list of rare materials requested by Arkenfall's healers, artisans, and scholars.",
    questIds: [
      "quest-requisition-wisp-essence",
      "quest-requisition-linen-scraps",
      "quest-requisition-frostroot",
      "quest-requisition-venom-sacs",
      "quest-requisition-ember-fragments",
      "quest-requisition-relic-shards",
      "quest-requisition-nightglass",
      "quest-requisition-frosthearts",
      "quest-requisition-storm-essence",
      "quest-requisition-crown-shards",
      "quest-requisition-astral-glass",
      "quest-requisition-first-echoes",
    ],
  },
  {
    id: "questline-arkenfall-chronicle",
    title: "The Chronicle of Arkenfall",
    description: "A complete record of the twelve expeditions that carry Arkenfall's story beyond its gates.",
    questIds: [
      "quest-chronicle-windsong",
      "quest-chronicle-highlands",
      "quest-chronicle-highfall",
      "quest-chronicle-mirefen",
      "quest-chronicle-foundry",
      "quest-chronicle-reliquary",
      "quest-chronicle-nightglass",
      "quest-chronicle-expanse",
      "quest-chronicle-stormspire",
      "quest-chronicle-hollow-crown",
      "quest-chronicle-astral-scar",
      "quest-chronicle-world-below",
    ],
  },
];
